#!/usr/bin/env Rscript

# =============================================================================
# Differential Transcript Expression Analysis with DESeq2
# =============================================================================
#
# Purpose:
#   This script performs differential transcript expression (DTE) analysis using
#   isoform-level count matrices generated from long-read RNA-seq data.
#
# Input:
#   - all_transcripts_with_associated_genes_count.tsv
#     generated by Generating_Count_Matrix.R
#
# Outputs:
#   - Counts_filtered.tsv
#   - DESeq2_sample_metadata.csv
#   - dds_full_object.rds
#   - vsd_full_object.rds
#   - DESeq2_normalized_counts.csv
#   - C3_vs_C0_isoform_results.csv
#   - C7_vs_C0_isoform_results.csv
#   - C7_vs_C3_isoform_results.csv
#
#
# =============================================================================

suppressPackageStartupMessages({
  library(tidyverse)
  library(DESeq2)
})

# -----------------------------
# User-defined files/directories
# -----------------------------

results_dir <- "/path/to/output_directory"                         # <-- MODIFY HERE

count_path <- file.path(
  results_dir,
  "all_transcripts_with_associated_genes_count.tsv"
)                                                                   # <-- MODIFY HERE IF NEEDED

dir.create(results_dir, recursive = TRUE, showWarnings = FALSE)

# -----------------------------
# User-adjustable parameters
# -----------------------------

min_count <- 10                                                     # <-- MODIFY HERE IF NEEDED
min_reps <- 2                                                       # <-- MODIFY HERE IF NEEDED

padj_cutoff <- 0.05                                                 # <-- MODIFY HERE IF NEEDED
lfc_cutoff <- 1                                                     # <-- MODIFY HERE IF NEEDED

# -----------------------------
# Input check
# -----------------------------

if (!file.exists(count_path)) {
  stop("Count matrix not found: ", count_path)
}

# =============================================================================
# Read annotated isoform count table
# =============================================================================

counts_raw <- readr::read_tsv(count_path, show_col_types = FALSE)

required_metadata_cols <- c(
  "transcript_id",
  "transcript_symbol",
  "associated_gene",
  "gene_symbol"
)

missing_cols <- setdiff(required_metadata_cols, colnames(counts_raw))

if (length(missing_cols) > 0) {
  stop(
    "Missing required metadata columns in count table: ",
    paste(missing_cols, collapse = ", ")
  )
}

# Expected format:
#   transcript_id, transcript_symbol, associated_gene, gene_symbol, sample columns...
sample_cols <- setdiff(colnames(counts_raw), required_metadata_cols)

# =============================================================================
# Filter lowly expressed isoforms
# =============================================================================
#
# Retain isoforms with >= min_count counts in at least min_reps biological
# replicates of any condition.

counts_filtered <- counts_raw %>%
  mutate(
    C0_ge_min = rowSums(across(starts_with("C0_Control_"), ~ .x >= min_count)) >= min_reps,
    C3_ge_min = rowSums(across(starts_with("C3_Injured_"), ~ .x >= min_count)) >= min_reps,
    C7_ge_min = rowSums(across(starts_with("C7_Injured_"), ~ .x >= min_count)) >= min_reps,
    keep = C0_ge_min | C3_ge_min | C7_ge_min
  ) %>%
  filter(keep) %>%
  select(-C0_ge_min, -C3_ge_min, -C7_ge_min, -keep)

readr::write_tsv(
  counts_filtered,
  file.path(results_dir, "Counts_filtered.tsv")
)

message("Isoforms retained after filtering: ", nrow(counts_filtered))

# =============================================================================
# Prepare DESeq2 count matrix and sample metadata
# =============================================================================

sample_cols <- setdiff(colnames(counts_filtered), required_metadata_cols)

count_data <- counts_filtered %>%
  select(all_of(sample_cols)) %>%
  mutate(across(everything(), round)) %>%
  as.data.frame()

rownames(count_data) <- counts_filtered$transcript_id

sample_info <- tibble(sample = sample_cols) %>%
  mutate(
    time_point = sub("^(C[0-9]+).*", "\\1", sample),
    treatment = case_when(
      str_detect(sample, "Injured") ~ "Injured",
      str_detect(sample, "Control") ~ "Control",
      TRUE ~ "Baseline"
    ),
    group = factor(
      paste0(time_point, "_", treatment),
      levels = c("C0_Control", "C3_Injured", "C7_Injured")
    )
  ) %>%
  as.data.frame()

rownames(sample_info) <- sample_info$sample

if (any(is.na(sample_info$group))) {
  stop("Some samples could not be assigned to groups. Check sample names.")
}

readr::write_csv(
  sample_info,
  file.path(results_dir, "DESeq2_sample_metadata.csv")
)

# =============================================================================
# Run DESeq2
# =============================================================================

dds <- DESeqDataSetFromMatrix(
  countData = count_data,
  colData = sample_info,
  design = ~ group
)

dds <- DESeq(dds)

saveRDS(
  dds,
  file.path(results_dir, "dds_full_object.rds")
)

vsd <- varianceStabilizingTransformation(dds, blind = FALSE)

saveRDS(
  vsd,
  file.path(results_dir, "vsd_full_object.rds")
)

# =============================================================================
# Extract contrast-level DESeq2 results
# =============================================================================

extract_deseq_results <- function(dds, numerator, denominator, annotation_tbl) {
  res <- results(
    dds,
    contrast = c("group", numerator, denominator),
    cooksCutoff = FALSE  # Note: Cook's distance filtering is disabled
  ) %>%
    as.data.frame()

  norm_counts <- counts(dds, normalized = TRUE)

  res %>%
    rownames_to_column("transcript_id") %>%
    mutate(
      transcript_symbol = annotation_tbl$transcript_symbol[
        match(transcript_id, annotation_tbl$transcript_id)
      ],
      associated_gene = annotation_tbl$associated_gene[
        match(transcript_id, annotation_tbl$transcript_id)
      ],
      gene_symbol = annotation_tbl$gene_symbol[
        match(transcript_id, annotation_tbl$transcript_id)
      ],
      mean_num = rowMeans(
        norm_counts[, colData(dds)$group == numerator, drop = FALSE]
      ),
      mean_den = rowMeans(
        norm_counts[, colData(dds)$group == denominator, drop = FALSE]
      ),
      significant = if_else(
        !is.na(padj) & padj <= padj_cutoff & abs(log2FoldChange) >= lfc_cutoff,
        TRUE,
        FALSE
      )
    ) %>%
    select(
      transcript_id,
      transcript_symbol,
      associated_gene,
      gene_symbol,
      baseMean,
      log2FoldChange,
      lfcSE,
      stat,
      pvalue,
      padj,
      mean_num,
      mean_den,
      significant
    ) %>%
    arrange(padj)
}

result_list <- list(
  C3_vs_C0 = extract_deseq_results(
    dds,
    numerator = "C3_Injured",
    denominator = "C0_Control",
    annotation_tbl = counts_filtered
  ),
  C7_vs_C0 = extract_deseq_results(
    dds,
    numerator = "C7_Injured",
    denominator = "C0_Control",
    annotation_tbl = counts_filtered
  ),
  C7_vs_C3 = extract_deseq_results(
    dds,
    numerator = "C7_Injured",
    denominator = "C3_Injured",
    annotation_tbl = counts_filtered
  )
)

purrr::walk2(
  result_list,
  names(result_list),
  ~ readr::write_csv(
    .x,
    file.path(results_dir, paste0(.y, "_isoform_results.csv"))
  )
)

# =============================================================================
# Export significant DET tables
# =============================================================================

purrr::walk2(
  result_list,
  names(result_list),
  ~ readr::write_csv(
    .x %>%
      filter(significant),
    file.path(results_dir, paste0(.y, "_significant_DETs.csv"))
  )
)

# =============================================================================
# Export normalized counts for plotting/source data
# =============================================================================

normalized_counts <- counts(dds, normalized = TRUE) %>%
  as.data.frame() %>%
  rownames_to_column("transcript_id") %>%
  left_join(
    counts_filtered %>%
      select(transcript_id, transcript_symbol, associated_gene, gene_symbol),
    by = "transcript_id"
  ) %>%
  relocate(
    transcript_symbol,
    associated_gene,
    gene_symbol,
    .after = transcript_id
  )

readr::write_csv(
  normalized_counts,
  file.path(results_dir, "DESeq2_normalized_counts.csv")
)

message("DTE analysis complete. Results saved to: ", results_dir)
