#!/usr/bin/env Rscript

# =============================================================================
# Generate unified isoform-level count matrix from SQANTI3 outputs
# =============================================================================
#
# Purpose:
#   This script:
#     1. Adds rescue flags to SQANTI3 classification tables
#     2. Filters SQANTI3 transcript abundances to rescue-supported isoforms
#     3. Unifies sample-specific novel transcript IDs
#     4. Merges per-sample abundance estimates into one count matrix
#     5. Annotates transcripts and genes using SQANTI3 output and BioMart
#
# Required inputs:
#   - SQANTI3 abundance.tsv files
#   - SQANTI3 classification files
#   - SQANTI3 rescue inclusion-list files
#   - novel_isoform_translation.csv generated by:
#       Unifying_Novel_Transcript_Names.R
#
# Usage:
#   Rscript Generating_Count_Matrix.R
#
# =============================================================================

suppressPackageStartupMessages({
  library(dplyr)
  library(purrr)
  library(readr)
  library(stringr)
  library(tibble)
  library(tidyr)
  library(biomaRt)
})

# -----------------------------
# User-defined directories
# -----------------------------

project_dir <- "/path/to/project_directory"          # <-- MODIFY HERE
results_dir <- file.path(project_dir, "results")    # <-- MODIFY HERE

dir.create(results_dir, recursive = TRUE, showWarnings = FALSE)

# -----------------------------
# Input files
# -----------------------------

lookup_file <- file.path(
  results_dir,
  "novel_isoform_translation.csv"
)                                                     # <-- MODIFY HERE IF NEEDED

sample_tbl <- tibble::tribble(
  ~sample_name,   ~abundance_file, ~class_file, ~rescue_file,

  "Sample_1",
  "/path/to/Sample_1/abundance.tsv",              # <-- MODIFY HERE
  "/path/to/Sample_1_classification.txt",         # <-- MODIFY HERE
  "/path/to/Sample_1_rescue.tsv",                 # <-- MODIFY HERE

  "Sample_2",
  "/path/to/Sample_2/abundance.tsv",              # <-- MODIFY HERE
  "/path/to/Sample_2_classification.txt",         # <-- MODIFY HERE
  "/path/to/Sample_2_rescue.tsv"                 # <-- MODIFY HERE
)

sample_tbl <- sample_tbl %>%
  mutate(
    rescued_class_file = file.path(
      results_dir,
      paste0(sample_name, "_classification_with_rescue.tsv")
    ),
    unified_abundance_file = file.path(
      results_dir,
      paste0(sample_name, "_abundance_unified.tsv")
    )
  )

# -----------------------------
# Helper functions
# -----------------------------

check_files_exist <- function(paths, label) {
  missing_paths <- paths[!file.exists(paths)]

  if (length(missing_paths) > 0) {
    stop(
      "Missing ", label, " file(s):\n",
      paste(missing_paths, collapse = "\n"),
      call. = FALSE
    )
  }

  invisible(TRUE)
}

strip_ensembl_version <- function(x) {
  stringr::str_remove(x, "\\.\\d+$")
}

read_rescue_ids <- function(path) {
  readr::read_tsv(path, col_names = FALSE, show_col_types = FALSE)[[1]] %>%
    unique()
}

add_rescue_flag <- function(class_path, rescue_path, out_path) {
  cls <- readr::read_tsv(class_path, show_col_types = FALSE)
  rescued_ids <- read_rescue_ids(rescue_path)

  cls_rescued <- cls %>%
    mutate(
      filter_rescued_result = if_else(
        filter_result == "Isoform" | isoform %in% rescued_ids,
        "Isoform",
        "Artifact"
      )
    )

  readr::write_tsv(cls_rescued, out_path)
  message("Saved rescue-flagged classification: ", out_path)

  invisible(out_path)
}

unify_sample_abundance <- function(abundance_file,
                                   rescued_class_file,
                                   lookup_tbl,
                                   sample_index,
                                   out_file) {

  valid_isoforms <- readr::read_tsv(
    rescued_class_file,
    show_col_types = FALSE
  ) %>%
    filter(filter_rescued_result == "Isoform") %>%
    pull(isoform) %>%
    unique()

  abundance_unified <- readr::read_tsv(
    abundance_file,
    show_col_types = FALSE
  ) %>%
    mutate(
      base_id = target_id,
      lookup_id = paste0(base_id, "_sample", sample_index)
    ) %>%
    filter(base_id %in% valid_isoforms) %>%
    left_join(lookup_tbl, by = c("lookup_id" = "transcript_id")) %>%
    mutate(
      transcript_id = coalesce(unified_id, base_id)
    ) %>%
    select(
      transcript_id,
      everything(),
      -unified_id,
      -lookup_id,
      -base_id
    )

  readr::write_tsv(abundance_unified, out_file)

  message("Wrote unified abundance file: ", out_file)

  invisible(out_file)
}

# -----------------------------
# Input checks
# -----------------------------

check_files_exist(sample_tbl$abundance_file, "abundance")
check_files_exist(sample_tbl$class_file, "SQANTI3 classification")
check_files_exist(sample_tbl$rescue_file, "rescue inclusion-list")
check_files_exist(lookup_file, "novel isoform translation lookup")

# -----------------------------
# Step 1: Add rescue flags
# -----------------------------

pwalk(
  sample_tbl %>%
    select(class_file, rescue_file, rescued_class_file),
  add_rescue_flag
)

# -----------------------------
# Step 2: Filter and unify abundance files
# -----------------------------

lookup_tbl <- readr::read_csv(
  lookup_file,
  show_col_types = FALSE
) %>%
  select(unified_id, transcript_id)

pwalk(
  sample_tbl %>%
    mutate(sample_index = row_number()) %>%
    select(
      abundance_file,
      rescued_class_file,
      sample_index,
      unified_abundance_file
    ),
  function(abundance_file,
           rescued_class_file,
           sample_index,
           unified_abundance_file) {

    unify_sample_abundance(
      abundance_file = abundance_file,
      rescued_class_file = rescued_class_file,
      lookup_tbl = lookup_tbl,
      sample_index = sample_index,
      out_file = unified_abundance_file
    )
  }
)

# -----------------------------
# Step 3: Merge abundance tables
# -----------------------------

sample_dfs <- map2(
  sample_tbl$unified_abundance_file,
  sample_tbl$sample_name,
  function(path, sample_name) {

    readr::read_tsv(path, show_col_types = FALSE) %>%
      filter(!str_starts(transcript_id, "transcript")) %>%
      select(transcript_id, est_counts) %>%   # Change to tpm if want TPM Matrix
      rename(!!sample_name := est_counts)  # Change to tpm if want TPM Matrix
  }
)

combined_counts <- reduce(sample_dfs, full_join, by = "transcript_id") %>%
  mutate(across(-transcript_id, as.numeric)) %>%
  replace_na(
    as.list(
      setNames(
        rep(0, nrow(sample_tbl)),
        sample_tbl$sample_name
      )
    )
  )

# -----------------------------
# Step 4: Extract transcript-to-gene mappings
# -----------------------------

class_df <- map_dfr(
  sample_tbl$rescued_class_file,
  readr::read_tsv,
  show_col_types = FALSE
) %>%
  filter(filter_rescued_result == "Isoform") %>%
  transmute(
    transcript_id = isoform,
    associated_gene = associated_gene
  ) %>%
  distinct(transcript_id, associated_gene)

annotated <- combined_counts %>%
  left_join(class_df, by = "transcript_id") %>%
  mutate(
    associated_gene = strip_ensembl_version(associated_gene),
    associated_gene = if_else(
      str_starts(transcript_id, "ENSMUST"),
      associated_gene,
      str_remove(transcript_id, "-novel.*$")
    )
  )

# -----------------------------
# Step 5: Add gene symbols from BioMart
# -----------------------------

genes_to_lookup <- annotated %>%
  filter(str_starts(associated_gene, "ENSMUSG")) %>%
  pull(associated_gene) %>%
  unique()

ensembl <- biomaRt::useMart(
  "ensembl",
  dataset = "mmusculus_gene_ensembl"
)

gene_map <- biomaRt::getBM(
  attributes = c("ensembl_gene_id", "external_gene_name"),
  filters = "ensembl_gene_id",
  values = genes_to_lookup,
  mart = ensembl
) %>%
  as_tibble() %>%
  rename(
    associated_gene = ensembl_gene_id,
    gene_symbol = external_gene_name
  )

final_tbl <- annotated %>%
  left_join(gene_map, by = "associated_gene") %>%
  mutate(
    gene_symbol = coalesce(gene_symbol, associated_gene)
  )

# -----------------------------
# Step 6: Add transcript symbols from BioMart
# -----------------------------

final_tbl <- final_tbl %>%
  mutate(
    transcript_core_for_biomart = if_else(
      str_starts(transcript_id, "ENSMUST"),
      strip_ensembl_version(transcript_id),
      NA_character_
    )
  )

tx_map <- biomaRt::getBM(
  attributes = c("ensembl_transcript_id", "external_transcript_name"),
  filters = "ensembl_transcript_id",
  values = unique(
    na.omit(final_tbl$transcript_core_for_biomart)
  ),
  mart = ensembl
) %>%
  as_tibble() %>%
  rename(
    transcript_core_for_biomart = ensembl_transcript_id,
    transcript_symbol = external_transcript_name
  )

final_tbl <- final_tbl %>%
  left_join(tx_map, by = "transcript_core_for_biomart") %>%
  mutate(
    transcript_symbol = coalesce(transcript_symbol, transcript_id),
    gene_symbol = if_else(
      is.na(gene_symbol) | gene_symbol == "",
      associated_gene,
      gene_symbol
    )
  ) %>%
  select(
    transcript_id,
    transcript_symbol,
    associated_gene,
    gene_symbol,
    everything(),
    -transcript_core_for_biomart
  )

# -----------------------------
# Step 7: Save final matrix
# -----------------------------

out_file <- file.path(
  results_dir,
  "all_transcripts_with_associated_genes_count.tsv"
)

readr::write_tsv(final_tbl, out_file)

message("Wrote final count matrix: ", out_file)
