#!/usr/bin/env Rscript

# =============================================================================
# Isoform-per-Gene Distribution across DGE, DTE and DTU Gene Sets
# =============================================================================
#
# Purpose:
#   This script counts the number of isoforms per gene in the filtered isoform
#   set tested for DTE, and summarizes how genes in each category (DGE and DTE,
#   DTE-only, DGE-only, DTU) are distributed by isoform number.
#
# Inputs:
#   - all_transcripts_with_associated_genes_count.tsv
#     generated by Generating_Isoform_Count_Matrix.R
#   - C3_vs_C0_isoform_results.csv, C7_vs_C0_isoform_results.csv
#     generated by DTE_Analysis_DESeq2.R
#   - C3_vs_C0_inferred_gene_results.csv, C7_vs_C0_inferred_gene_results.csv
#     generated by Gene_Analysis/DGE_Analysis_Long_Read.R
#   - All_Isoform_Switching_Events_Annotated.csv
#     generated by DTU_Analysis_IsoformSwitchAnalyzeR_DEXSeq.R
#
# Output:
#   - Isoform_per_gene_distribution_C3_C7.csv
#
# =============================================================================

suppressPackageStartupMessages({
  library(tidyverse)
})

# -----------------------------
# User-defined files/directories
# -----------------------------

results_dir <- "/path/to/isoform_analysis_results"                 # <-- MODIFY HERE

dtu_path <- "/path/to/All_Isoform_Switching_Events_Annotated.csv"  # <-- MODIFY HERE

count_path <- file.path(
  results_dir,
  "all_transcripts_with_associated_genes_count.tsv"
)                                                                   # <-- MODIFY HERE IF NEEDED

output_path <- file.path(
  results_dir,
  "Isoform_per_gene_distribution_C3_C7.csv"
)                                                                   # <-- MODIFY HERE IF NEEDED

# -----------------------------
# User-adjustable parameters
# -----------------------------

padj_cutoff <- 0.05                                                 # <-- MODIFY HERE IF NEEDED
lfc_cutoff <- 1                                                     # <-- MODIFY HERE IF NEEDED
dIF_cutoff <- 0.1                                                   # <-- MODIFY HERE IF NEEDED

comparisons <- c("C3", "C7")

# -----------------------------
# Input checks
# -----------------------------

required_files <- c(
  count_path,
  dtu_path,
  file.path(results_dir, paste0(comparisons, "_vs_C0_isoform_results.csv")),
  file.path(results_dir, paste0(comparisons, "_vs_C0_inferred_gene_results.csv"))
)

missing_files <- required_files[!file.exists(required_files)]

if (length(missing_files) > 0) {
  stop(
    "Missing required file(s):\n",
    paste(missing_files, collapse = "\n"),
    call. = FALSE
  )
}

# =============================================================================
# Helper functions
# =============================================================================

# Removes the version suffix (e.g. ".1") from Ensembl IDs so that the count
# table and DESeq2 result tables share the same transcript identifiers.
strip_ensembl_version <- function(x) {
  if_else(str_starts(x, "ENSMUS"), str_remove(x, "\\.\\d+$"), x)
}

is_ensembl_gene <- function(x) {
  !is.na(x) & str_starts(x, "ENSMUSG")
}

read_isoform_results <- function(comparison) {
  readr::read_csv(
    file.path(results_dir, paste0(comparison, "_vs_C0_isoform_results.csv")),
    show_col_types = FALSE
  ) %>%
    mutate(transcript_id = strip_ensembl_version(transcript_id)) %>%
    left_join(transcript_gene_map, by = "transcript_id") %>%
    mutate(
      associated_gene = case_when(
        !is.na(mapped_associated_gene) ~ mapped_associated_gene,
        is_ensembl_gene(associated_gene) ~ associated_gene,
        TRUE ~ NA_character_
      )
    ) %>%
    dplyr::select(-mapped_associated_gene)
}

# =============================================================================
# Load annotation maps
# =============================================================================

counts_raw <- readr::read_tsv(count_path, show_col_types = FALSE) %>%
  mutate(transcript_id = strip_ensembl_version(transcript_id))

dtu_events <- readr::read_csv(dtu_path, show_col_types = FALSE)

transcript_gene_map <- counts_raw %>%
  filter(!is.na(transcript_id), is_ensembl_gene(associated_gene)) %>%
  distinct(transcript_id, mapped_associated_gene = associated_gene)

# Gene symbols mapping to more than one Ensembl gene ID are excluded.
gene_map_unique <- counts_raw %>%
  filter(!is.na(gene_symbol), is_ensembl_gene(associated_gene)) %>%
  distinct(gene_symbol, associated_gene) %>%
  group_by(gene_symbol) %>%
  filter(dplyr::n() == 1) %>%
  ungroup()

# =============================================================================
# Count isoforms per gene in the filtered isoform set
# =============================================================================

# Both result tables contain the same tested isoforms.
isoform_per_gene <- read_isoform_results(comparisons[1]) %>%
  filter(!is.na(associated_gene), !is.na(transcript_id)) %>%
  distinct(associated_gene, transcript_id) %>%
  dplyr::count(associated_gene, name = "n_isoforms")

# =============================================================================
# Define DGE, DTE and DTU gene sets for each comparison
# =============================================================================

get_comparison_sets <- function(comparison) {
  gene_sig <- readr::read_csv(
    file.path(results_dir, paste0(comparison, "_vs_C0_inferred_gene_results.csv")),
    show_col_types = FALSE
  ) %>%
    filter(!is.na(padj), padj <= padj_cutoff, abs(log2FoldChange) >= lfc_cutoff)

  transcript_sig <- read_isoform_results(comparison) %>%
    filter(!is.na(padj), padj <= padj_cutoff, abs(log2FoldChange) >= lfc_cutoff)

  dtu_sig <- dtu_events %>%
    filter(
      condition_1 == "C0",
      condition_2 == comparison,
      !is.na(padj),
      padj <= padj_cutoff,
      abs(dIF) >= dIF_cutoff
    ) %>%
    left_join(
      gene_map_unique %>%
        dplyr::rename(
          gene_id = gene_symbol,
          mapped_associated_gene = associated_gene
        ),
      by = "gene_id"
    ) %>%
    mutate(
      associated_gene = case_when(
        is_ensembl_gene(associated_gene) ~ associated_gene,
        !is.na(mapped_associated_gene) ~ mapped_associated_gene,
        TRUE ~ NA_character_
      )
    )

  dge_genes <- unique(na.omit(gene_sig$associated_gene))
  dte_genes <- unique(na.omit(transcript_sig$associated_gene))
  dtu_genes <- unique(na.omit(dtu_sig$associated_gene))

  bind_rows(
    tibble(associated_gene = intersect(dge_genes, dte_genes), group = "DGE ∩ DTE"),
    tibble(associated_gene = setdiff(dte_genes, dge_genes), group = "DTE-only"),
    tibble(associated_gene = setdiff(dge_genes, dte_genes), group = "DGE-only"),
    tibble(associated_gene = dtu_genes, group = "DTU")
  ) %>%
    mutate(comparison = paste0(comparison, " vs C0"))
}

all_sets <- bind_rows(
  isoform_per_gene %>%
    transmute(
      associated_gene,
      group = "All genes",
      comparison = "All analyzed genes"
    ),
  purrr::map_dfr(comparisons, get_comparison_sets)
)

# =============================================================================
# Summarize isoform-per-gene distribution
# =============================================================================

isoform_set_df <- all_sets %>%
  left_join(isoform_per_gene, by = "associated_gene")

# Genes without an isoform in the filtered isoform set have no isoform count
# and are not included in the distribution table.
n_without_count <- sum(is.na(isoform_set_df$n_isoforms))

if (n_without_count > 0) {
  message("Gene-set entries without an isoform count (excluded): ", n_without_count)
}

isoform_distribution_table <- isoform_set_df %>%
  filter(!is.na(n_isoforms)) %>%
  mutate(
    isoform_bin = factor(
      if_else(n_isoforms >= 6, "6+", as.character(n_isoforms)),
      levels = c("1", "2", "3", "4", "5", "6+")
    )
  ) %>%
  dplyr::count(comparison, group, isoform_bin, name = "n_genes") %>%
  group_by(comparison, group) %>%
  mutate(
    total_genes = sum(n_genes),
    percent = 100 * n_genes / total_genes
  ) %>%
  ungroup()

isoform_distribution_wide <- isoform_distribution_table %>%
  mutate(value = paste0(n_genes, " (", sprintf("%.1f", percent), "%)")) %>%
  dplyr::select(comparison, group, isoform_bin, value) %>%
  pivot_wider(
    names_from = isoform_bin,
    values_from = value,
    values_fill = "0 (0.0%)"
  ) %>%
  arrange(
    factor(comparison, levels = c("All analyzed genes", paste0(comparisons, " vs C0"))),
    factor(group, levels = c("All genes", "DGE ∩ DTE", "DTE-only", "DGE-only", "DTU"))
  )

readr::write_csv(isoform_distribution_wide, output_path)

message("Isoform-per-gene distribution saved to: ", output_path)
