#!/usr/bin/env Rscript

# =============================================================================
# Cell-type enrichment of multi-DET genes in pseudobulk DEGs
# =============================================================================
#
# Purpose:
#   This script tests whether genes with multiple differentially expressed
#   transcripts (multi-DET genes) are enriched among cell-type-specific
#   pseudobulk DEGs, using logistic regression adjusted for bulk expression,
#   cell-type expression and isoform number (two-sided Wald test):
#
#     is_DEG ~ multiDET + log_expr + log_expr_ct + log2(n_iso)
#
#   The universe for each cell type is the set of genes with >= 2 tested
#   isoforms in the bulk isoform analysis that were also tested in that cell
#   type's pseudobulk analysis.
#
# Inputs:
#   - C3_vs_C0_isoform_results.csv, C7_vs_C0_isoform_results.csv
#     generated by Isoform_Analysis/DTE_Analysis_DESeq2.R
#   - DE_<cell_type>_<contrast>.csv pseudobulk DESeq2 results
#     generated by Integration_and_Pseudobulk_DESeq2.R
#
# Output:
#   - multi_DET_cell_type_enrichment_results.csv
#
# =============================================================================

suppressPackageStartupMessages({
  library(tidyverse)
})

# -----------------------------
# User-defined files/directories
# -----------------------------

single_cell_results_dir <- "/path/to/single_cell_results"        # <-- MODIFY HERE
isoform_results_dir <- "/path/to/isoform_analysis_results"       # <-- MODIFY HERE
outdir <- single_cell_results_dir                                # <-- MODIFY HERE IF NEEDED

dir.create(outdir, recursive = TRUE, showWarnings = FALSE)

# -----------------------------
# User-defined input files
# -----------------------------

isoform_results_paths <- c(
  C3_vs_C0 = file.path(isoform_results_dir, "C3_vs_C0_isoform_results.csv"),
  C7_vs_C0 = file.path(isoform_results_dir, "C7_vs_C0_isoform_results.csv")
)                                                                 # <-- MODIFY HERE IF NEEDED

# -----------------------------
# User-adjustable thresholds
# -----------------------------

padj_cutoff <- 0.05                                               # <-- MODIFY HERE IF NEEDED
lfc_cutoff <- 1                                                   # <-- MODIFY HERE IF NEEDED

# -----------------------------
# Input checks
# -----------------------------

missing_files <- isoform_results_paths[!file.exists(isoform_results_paths)]

if (length(missing_files) > 0) {
  stop(
    "Missing required file(s):\n",
    paste(missing_files, collapse = "\n"),
    call. = FALSE
  )
}

# -----------------------------
# Helper functions
# -----------------------------

# Per-gene isoform number, multi-DET status and bulk expression
get_gene_isoform_summary <- function(det_path) {
  det_all <- readr::read_csv(det_path, show_col_types = FALSE) %>%
    filter(!is.na(gene_symbol), gene_symbol != "")

  required_cols <- c("gene_symbol", "transcript_id", "baseMean", "log2FoldChange", "padj")
  missing_cols <- setdiff(required_cols, colnames(det_all))

  if (length(missing_cols) > 0) {
    stop(
      "Isoform results file is missing column(s): ",
      paste(missing_cols, collapse = ", "),
      call. = FALSE
    )
  }

  # Bulk gene expression: sum of isoform baseMean
  bulk_expr <- det_all %>%
    group_by(gene_symbol) %>%
    summarise(log_expr = log2(sum(baseMean, na.rm = TRUE) + 1), .groups = "drop")

  # Genes with a single tested isoform cannot be multi-DET and are excluded
  det_all %>%
    filter(!is.na(padj)) %>%
    group_by(gene_symbol) %>%
    summarise(
      n_iso = n_distinct(transcript_id),
      n_det = n_distinct(
        transcript_id[padj < padj_cutoff & abs(log2FoldChange) >= lfc_cutoff]
      ),
      .groups = "drop"
    ) %>%
    filter(n_iso >= 2) %>%
    mutate(multiDET = as.integer(n_det >= 2)) %>%
    inner_join(bulk_expr, by = "gene_symbol")
}

read_pseudobulk_results <- function(path) {
  readr::read_csv(path, show_col_types = FALSE) %>%
    filter(!is.na(gene), !is.na(padj)) %>%
    transmute(
      gene_symbol = gene,
      log_expr_ct = log2(baseMean + 1),
      is_DEG = as.integer(padj < padj_cutoff & abs(log2FoldChange) >= lfc_cutoff)
    ) %>%
    distinct(gene_symbol, .keep_all = TRUE)
}

test_cell_type_enrichment <- function(gene_summary, deg, cell_type) {
  # Per-cell-type universe: multi-isoform genes also tested in this cell type
  df <- inner_join(gene_summary, deg, by = "gene_symbol")

  out <- tibble(
    cell_type = cell_type,
    universe = nrow(df),
    n_multiDET = sum(df$multiDET),
    n_deg = sum(df$is_DEG),
    overlap = sum(df$multiDET == 1 & df$is_DEG == 1),
    adj_or = NA_real_,
    adj_ci_low = NA_real_,
    adj_ci_high = NA_real_,
    adj_p = NA_real_
  )

  # Both variables must vary to fit the model
  if (out$n_multiDET %in% c(0, out$universe) || out$n_deg %in% c(0, out$universe)) {
    return(out)
  }

  fit <- glm(
    is_DEG ~ multiDET + log_expr + log_expr_ct + log2(n_iso),
    data = df,
    family = binomial
  )

  coefs <- summary(fit)$coefficients

  if ("multiDET" %in% rownames(coefs)) {
    ci <- confint.default(fit)["multiDET", ]

    out$adj_or <- exp(coefs["multiDET", "Estimate"])
    out$adj_ci_low <- exp(ci[1])
    out$adj_ci_high <- exp(ci[2])
    out$adj_p <- coefs["multiDET", "Pr(>|z|)"]
  }

  out
}

run_enrichment <- function(det_path, contrast) {
  gene_summary <- get_gene_isoform_summary(det_path)

  pseudobulk_files <- list.files(
    single_cell_results_dir,
    pattern = paste0("^DE_.*_", contrast, "\\.csv$"),
    full.names = TRUE
  )

  if (length(pseudobulk_files) == 0) {
    stop(
      "No pseudobulk DESeq2 files found for ", contrast, " in: ",
      single_cell_results_dir,
      call. = FALSE
    )
  }

  message(contrast, ": ", length(pseudobulk_files), " pseudobulk DESeq2 files")

  purrr::map_dfr(pseudobulk_files, function(file) {
    cell_type <- basename(file) %>%
      str_remove("^DE_") %>%
      str_remove(paste0("_", contrast, "\\.csv$")) %>%
      str_replace_all("_", " ")

    test_cell_type_enrichment(
      gene_summary = gene_summary,
      deg = read_pseudobulk_results(file),
      cell_type = cell_type
    )
  }) %>%
    mutate(
      contrast = contrast,
      adj_padj = p.adjust(adj_p, method = "BH")
    )
}

# -----------------------------
# Run enrichment
# -----------------------------

enrichment_results <- purrr::imap_dfr(isoform_results_paths, run_enrichment) %>%
  relocate(contrast) %>%
  arrange(contrast, adj_padj)

readr::write_csv(
  enrichment_results,
  file.path(outdir, "multi_DET_cell_type_enrichment_results.csv")
)

message("Cell-type enrichment analysis complete.")
