#!/bin/bash

# =============================================================================
# Build custom Cell Ranger reference with split Mbp annotations
# =============================================================================
#
# Purpose:
#   This script runs cellranger mkref to generate a custom GRCm39 reference
#   containing separate Mbp_Golli and Mbp_Compact gene models.
#
# Docker image used:
#   jinlab/velocytoxcellranger:vs0.17.17x9.0.1
#
# Input:
#   - genome FASTA
#   - modified GTF generated by:
#       Creating_new_reference_for_Golli_Compact_Mbp.sh
#
# Output:
#   - GRCm39_MbpSplit Cell Ranger reference directory
#
# =============================================================================

set -euo pipefail

# -----------------------------
# User-defined paths
# -----------------------------

GENOME_NAME="GRCm39_MbpSplit"                                  # <-- MODIFY HERE IF NEEDED

GENOME_FASTA="/path/to/refdata-gex-GRCm39-2024-A/fasta/genome.fa" # <-- MODIFY HERE
GENES_GTF="/path/to/genes.MbpSplit.gtf"                         # <-- MODIFY HERE

MEM_GB=64                                                       # <-- MODIFY HERE IF NEEDED

# -----------------------------
# Run Cell Ranger mkref
# -----------------------------

cellranger mkref \
  --genome="${GENOME_NAME}" \
  --fasta="${GENOME_FASTA}" \
  --genes="${GENES_GTF}" \
  --memgb="${MEM_GB}"
