#!/usr/bin/env Rscript

################################################################################
# Figure 2: Peripheral nerve injury induces widespread isoform remodeling with
#  distinct modes of transcript emergence and functional consequences.
#
# Panels generated by this script:
#   A: DET distribution by direction and protein-coding status
#   B: Genes with single versus multiple DETs
#   C: GO enrichment of multi-DET genes at C3 and C7
#      (background: multi-isoform genes)
#   D: Emergence categories of DETs
#   E: Structural remodeling categories among emerged-remodeling DETs
#
# Panels F - H are generated using:
#     Plotting_isoform_expression.R
#     Plotting_isoform_proportion.R
#     Plotting_isoform_trackplot.R
#
# Inputs:
#   - all_transcripts_with_associated_genes_count.tsv
#       from Isoform_Analysis/Generating_Isoform_Count_Matrix.R
#   - Counts_filtered.tsv, C3_vs_C0_isoform_results.csv and
#     C7_vs_C0_isoform_results.csv
#       from Isoform_Analysis/DTE_Analysis_DESeq2.R
#   - Ensembl reference GTF (GRCm39 release 115)
#   - renamed transcript GTF files from SQANTI3 to reflect novel transcripts
#   - SQANTI3 classification files (filtered, with rescue flag)
#
################################################################################

suppressPackageStartupMessages({
  library(rtracklayer)
  library(clusterProfiler)
  library(org.Mm.eg.db)
  library(tidyverse)
  library(patchwork)
  library(scales)
  library(grid)
})

# ==============================================================================
# User-defined files/directories
# ==============================================================================

results_dir <- "/path/to/isoform_analysis_results"               # <-- MODIFY HERE

ref_gtf_path <- "/path/to/Mus_musculus.GRCm39.115.gtf"           # <-- MODIFY HERE

renamed_gtf_dir <- "/path/to/renamed_or_unified_gtf_files"       # <-- MODIFY HERE

sqanti_class_dir <- "/path/to/SQANTI3_classification_files"      # <-- MODIFY HERE
sqanti_class_pattern <- "classification_with_rescue_flag_with_transcriptID\\.txt$"  # <-- MODIFY HERE IF NEEDED

figure_dir <- "/path/to/Figure_2_output"                         # <-- MODIFY HERE

dir.create(figure_dir, recursive = TRUE, showWarnings = FALSE)

# ==============================================================================
# Input files
# ==============================================================================

count_path <- file.path(
  results_dir,
  "all_transcripts_with_associated_genes_count.tsv"
)                                                                # <-- MODIFY HERE IF NEEDED

counts_filtered_path <- file.path(
  results_dir,
  "Counts_filtered.tsv"
)                                                                # <-- MODIFY HERE IF NEEDED

res_c3_path <- file.path(
  results_dir,
  "C3_vs_C0_isoform_results.csv"
)                                                                # <-- MODIFY HERE IF NEEDED

res_c7_path <- file.path(
  results_dir,
  "C7_vs_C0_isoform_results.csv"
)                                                                # <-- MODIFY HERE IF NEEDED

required_files <- c(
  count_path,
  counts_filtered_path,
  res_c3_path,
  res_c7_path,
  ref_gtf_path
)

missing_files <- required_files[!file.exists(required_files)]

if (length(missing_files) > 0) {
  stop(
    "Missing required file(s):\n",
    paste(missing_files, collapse = "\n"),
    call. = FALSE
  )
}

sqanti_class_files <- list.files(
  sqanti_class_dir,
  pattern = sqanti_class_pattern,
  full.names = TRUE
)

if (length(sqanti_class_files) == 0) {
  stop("No SQANTI3 classification files found in: ", sqanti_class_dir, call. = FALSE)
}

renamed_gtf_files <- list.files(
  renamed_gtf_dir,
  pattern = "\\.gtf$",
  full.names = TRUE
)

if (length(renamed_gtf_files) == 0) {
  stop("No GTF files found in: ", renamed_gtf_dir, call. = FALSE)
}

# ==============================================================================
# Parameters
# ==============================================================================

padj_cutoff <- 0.05                                               # <-- MODIFY HERE IF NEEDED
lfc_cutoff <- 1                                                   # <-- MODIFY HERE IF NEEDED

min_count <- 10                                                   # <-- MODIFY HERE IF NEEDED
min_reps <- 2                                                     # <-- MODIFY HERE IF NEEDED

go_ontology <- "BP"                                               # <-- MODIFY HERE IF NEEDED
go_top_n <- 8                                                     # <-- MODIFY HERE IF NEEDED
go_simplify_cutoff <- 0.6                                         # <-- MODIFY HERE IF NEEDED

comparison_levels <- c("C3 vs. C0", "C7 vs. C0")

comparison_colors <- c(
  "C3 vs. C0" = "#E69F00",
  "C7 vs. C0" = "#66BD63"
)

# Transcript biotypes counted as protein-coding in Figure 2A. Known transcripts
# use the Ensembl biotype; novel isoforms are labeled "novel_coding" or
# "novel_non_coding" from SQANTI3 ORF predictions.
coding_biotypes <- c(
  "protein_coding",
  "novel_coding"
)                                                                 # <-- MODIFY HERE IF NEEDED

transcript_class_levels <- c("Protein-coding", "Non-protein-coding")

transcript_class_alpha <- c(
  "Protein-coding" = 1,
  "Non-protein-coding" = 0.3
)

bar_half_width <- 0.42                                            # <-- MODIFY HERE IF NEEDED

remodel_class_levels <- c(
  "UTR Only",
  "Noncoding",
  "ORF Loss",
  "ORF Gain",
  "ORF Modification"
)

# ==============================================================================
# Helper functions
# ==============================================================================

theme_pub <- function(base_size = 7) {
  theme_classic(base_size = base_size) +
    theme(
      axis.line = element_line(color = "black", linewidth = 0.3),
      axis.ticks = element_line(color = "black", linewidth = 0.3),
      axis.ticks.length = unit(0.15, "cm"),
      panel.grid = element_blank(),
      axis.text.x = element_text(size = 5, hjust = 0.5, vjust = 0.5),
      axis.text.y = element_text(size = 5),
      axis.title.x = element_text(size = 6, margin = margin(t = 3)),
      axis.title.y = element_text(size = 6, margin = margin(r = 3)),
      plot.title = element_text(size = 7, face = "bold", hjust = 0.5, margin = margin(b = 4)),
      legend.key.size = unit(3, "mm"),
      legend.text = element_text(size = 5),
      legend.title = element_blank(),
      plot.margin = margin(t = 8, r = 4, b = 4, l = 4, unit = "mm")
    )
}

save_panel <- function(plot, filename, width_mm, height_mm) {
  ggsave(
    filename = file.path(figure_dir, filename),
    plot = plot,
    width = width_mm,
    height = height_mm,
    units = "mm",
    dpi = 600,
    bg = "white"
  )
}

pct_lab_frac <- function(x) sprintf("%.1f%%", 100 * x)
pct_lab_value <- function(x) sprintf("%.1f%%", x)

recode_contrast <- function(x) {
  dplyr::recode(x, "C3_vs_C0" = "C3 vs. C0", "C7_vs_C0" = "C7 vs. C0")
}

standardize_sample_name <- function(x) {
  case_when(
    str_detect(x, "^C0_Control_") ~ str_replace(x, "^C0_Control_(\\d+)$", "C0_Sciatic_\\1"),
    str_detect(x, "^C3_Injured_") ~ str_replace(x, "^C3_Injured_(\\d+)$", "C3_Injured_Sciatic_\\1"),
    str_detect(x, "^C7_Injured_") ~ str_replace(x, "^C7_Injured_(\\d+)$", "C7_Injured_Sciatic_\\1"),
    TRUE ~ x
  )
}

# Removes the version suffix (e.g. ".1") from Ensembl IDs so that the count
# table, DESeq2 results and reference GTF share the same transcript identifiers.
strip_ensembl_version <- function(x) {
  if_else(str_starts(x, "ENSMUS"), str_remove(x, "\\.\\d+$"), x)
}

get_significant_det <- function(res, contrast_label, padj_cut = padj_cutoff, lfc = lfc_cutoff) {
  res %>%
    mutate(contrast = contrast_label) %>%
    filter(!is.na(padj), padj <= padj_cut, abs(log2FoldChange) >= lfc) %>%
    transmute(
      contrast,
      contrast_pretty = recode_contrast(contrast),
      transcript_id,
      transcript_symbol,
      gene_symbol,
      log2FoldChange,
      padj,
      mean_den
    ) %>%
    distinct(transcript_symbol, contrast, .keep_all = TRUE)
}

filter_dets <- function(res, padj_cut = padj_cutoff, lfc = lfc_cutoff) {
  res %>%
    filter(!is.na(padj), padj <= padj_cut, abs(log2FoldChange) >= lfc)
}

# Known transcripts use the reference GTF biotype; novel transcripts, which have
# no reference biotype, use the SQANTI3 coding prediction.
annotate_transcript_class <- function(res, known_biotype, novel_coding) {
  res %>%
    left_join(known_biotype, by = "transcript_id") %>%
    left_join(novel_coding, by = "transcript_id") %>%
    mutate(
      biotype = case_when(
        !is.na(biotype) ~ biotype,
        coding == "coding" ~ "novel_coding",
        coding == "non_coding" ~ "novel_non_coding",
        TRUE ~ NA_character_
      ),
      transcript_class = factor(
        if_else(
          !is.na(biotype) & biotype %in% coding_biotypes,
          "Protein-coding",
          "Non-protein-coding"
        ),
        levels = transcript_class_levels
      )
    ) %>%
    dplyr::select(-coding)
}

count_det_direction <- function(res, comparison_label) {
  filter_dets(res) %>%
    mutate(direction = if_else(log2FoldChange > 0, "Up", "Down")) %>%
    dplyr::count(direction, transcript_class) %>%
    mutate(comparison = factor(comparison_label, levels = comparison_levels))
}

get_noncoding_dets <- function(res, comparison_label) {
  filter_dets(res) %>%
    filter(transcript_class == "Non-protein-coding") %>%
    mutate(
      direction = if_else(log2FoldChange > 0, "Increase", "Decrease"),
      comparison = comparison_label
    ) %>%
    dplyr::select(
      transcript_id,
      transcript_symbol,
      gene_symbol,
      biotype,
      direction,
      comparison,
      baseMean,
      log2FoldChange,
      lfcSE,
      stat,
      pvalue,
      padj
    ) %>%
    arrange(padj, dplyr::desc(abs(log2FoldChange)))
}

get_baseline_status <- function(counts_tbl, c0_cols, min_count = 10, min_reps = 2) {
  counts_tbl %>%
    mutate(
      n_C0_ge_min = rowSums(across(all_of(c0_cols), ~ .x >= min_count), na.rm = TRUE),
      iso_expressed_baseline = n_C0_ge_min >= min_reps
    ) %>%
    group_by(gene_symbol) %>%
    mutate(gene_has_any_baseline_isoform = any(iso_expressed_baseline)) %>%
    ungroup() %>%
    mutate(
      baseline_status = case_when(
        iso_expressed_baseline ~ "Expressed at Baseline",
        !iso_expressed_baseline & !gene_has_any_baseline_isoform ~ "Emerged: Activation",
        !iso_expressed_baseline & gene_has_any_baseline_isoform ~ "Emerged: Remodeling",
        TRUE ~ NA_character_
      )
    )
}

to_entrez <- function(symbols) {
  suppressMessages(
    bitr(
      unique(symbols),
      fromType = "SYMBOL",
      toType = "ENTREZID",
      OrgDb = org.Mm.eg.db
    )
  ) %>%
    pull(ENTREZID) %>%
    unique()
}

parse_gene_ratio <- function(x) {
  purrr::map_dbl(x, function(ratio) {
    parts <- str_split(ratio, "/", simplify = TRUE)
    as.numeric(parts[1]) / as.numeric(parts[2])
  })
}

plot_stacked_percent <- function(plot_df, x_var, fill_var, y_lab, title) {
  ggplot(plot_df, aes(x = {{ x_var }}, y = frac, fill = {{ fill_var }})) +
    geom_col(width = 0.9, color = "black", linewidth = 0.25) +
    geom_text(aes(label = pct_lab_frac(frac)), position = position_stack(vjust = 0.5), size = 2) +
    scale_y_continuous(labels = percent_format(accuracy = 1), expand = c(0, 0)) +
    labs(x = NULL, y = y_lab, title = title, fill = NULL) +
    theme_pub() +
    theme(
      legend.position = "bottom",
      legend.box = "horizontal",
      legend.text = element_text(size = 6),
      legend.spacing.y = unit(1, "mm"),
      legend.spacing.x = unit(1, "mm"),
      legend.box.margin = margin(t = -2, r = 0, b = 0, l = 0, unit = "mm")
    )
}

# Splits an exon into CDS and UTR segments using ORF genomic boundaries.
split_exon_by_orf <- function(exon_row) {
  exon <- as_tibble(exon_row)
  cds_start <- exon$CDS_genomic_start
  cds_end <- exon$CDS_genomic_end
  s <- exon$start
  e <- exon$end
  strand <- as.character(exon$strand)

  if (is.na(cds_start) || is.na(cds_end)) {
    exon$region_type <- "UTR"
    return(exon)
  }

  cds_low <- min(cds_start, cds_end)
  cds_high <- max(cds_start, cds_end)
  parts <- list()

  if (strand == "+") {
    if (s < cds_low) {
      parts[[length(parts) + 1]] <- exon %>% mutate(end = min(e, cds_low - 1), region_type = "5UTR")
    }
    if (e >= cds_low && s <= cds_high) {
      parts[[length(parts) + 1]] <- exon %>% mutate(start = max(s, cds_low), end = min(e, cds_high), region_type = "CDS")
    }
    if (e > cds_high) {
      parts[[length(parts) + 1]] <- exon %>% mutate(start = max(s, cds_high + 1), region_type = "3UTR")
    }
  } else if (strand == "-") {
    if (e > cds_high) {
      parts[[length(parts) + 1]] <- exon %>% mutate(start = max(s, cds_high + 1), region_type = "5UTR")
    }
    if (e >= cds_low && s <= cds_high) {
      parts[[length(parts) + 1]] <- exon %>% mutate(start = max(s, cds_low), end = min(e, cds_high), region_type = "CDS")
    }
    if (s < cds_low) {
      parts[[length(parts) + 1]] <- exon %>% mutate(end = min(e, cds_low - 1), region_type = "3UTR")
    }
  }

  bind_rows(parts) %>% filter(end >= start)
}

compare_tx_to_ref <- function(tx, ref_tx, structure_tbl) {
  tx_regions <- structure_tbl %>% filter(tx_id == tx)
  ref_regions <- structure_tbl %>% filter(tx_id == ref_tx)

  if (nrow(tx_regions) == 0 || nrow(ref_regions) == 0) {
    return(tibble(
      tx_id = tx,
      ref_tx = ref_tx,
      cds_changed = NA,
      utr_changed = NA,
      structure_change_class = "Coding-Noncoding Switch"
    ))
  }

  cds_changed <- !identical(
    tx_regions %>%
      filter(region_type == "CDS") %>%
      arrange(seqnames, start, end, strand) %>%
      dplyr::select(seqnames, start, end, strand),
    ref_regions %>%
      filter(region_type == "CDS") %>%
      arrange(seqnames, start, end, strand) %>%
      dplyr::select(seqnames, start, end, strand)
  )

  utr_changed <- !identical(
    tx_regions %>%
      filter(region_type == "UTR") %>%
      arrange(seqnames, start, end, strand) %>%
      dplyr::select(seqnames, start, end, strand),
    ref_regions %>%
      filter(region_type == "UTR") %>%
      arrange(seqnames, start, end, strand) %>%
      dplyr::select(seqnames, start, end, strand)
  )

  tibble(
    tx_id = tx,
    ref_tx = ref_tx,
    cds_changed = cds_changed,
    utr_changed = utr_changed,
    structure_change_class = case_when(
      cds_changed & utr_changed ~ "CDS + UTR",
      cds_changed & !utr_changed ~ "CDS only",
      !cds_changed & utr_changed ~ "UTR only",
      !cds_changed & !utr_changed ~ "No CDS/UTR change",
      TRUE ~ NA_character_
    )
  )
}

# ==============================================================================
# Load data
# ==============================================================================

counts_filtered <- read_tsv(counts_filtered_path, show_col_types = FALSE) %>%
  mutate(across(c(transcript_id, transcript_symbol), strip_ensembl_version))

res_list <- list(
  C3_vs_C0 = read_csv(res_c3_path, show_col_types = FALSE),
  C7_vs_C0 = read_csv(res_c7_path, show_col_types = FALSE)
) %>%
  purrr::map(~ mutate(.x, across(c(transcript_id, transcript_symbol), strip_ensembl_version)))

# ==============================================================================
# Annotate transcript coding status
# ==============================================================================

message("Importing reference GTF: ", ref_gtf_path)

ref_gtf <- rtracklayer::import(ref_gtf_path) %>% as.data.frame()

known_biotype <- ref_gtf %>%
  filter(type == "transcript") %>%
  transmute(
    transcript_id = strip_ensembl_version(transcript_id),
    biotype = transcript_biotype
  ) %>%
  distinct(transcript_id, .keep_all = TRUE)

# One coding call per novel transcript: the most frequent call across samples.
novel_coding <- map_dfr(
  sqanti_class_files,
  ~ read_tsv(.x, show_col_types = FALSE) %>%
    filter(filter_rescued_result == "Isoform") %>%
    dplyr::select(transcript_id, coding)
) %>%
  dplyr::count(transcript_id, coding) %>%
  group_by(transcript_id) %>%
  slice_max(n, n = 1, with_ties = FALSE) %>%
  ungroup() %>%
  dplyr::select(transcript_id, coding)

res_list$C3_vs_C0 <- annotate_transcript_class(res_list$C3_vs_C0, known_biotype, novel_coding)
res_list$C7_vs_C0 <- annotate_transcript_class(res_list$C7_vs_C0, known_biotype, novel_coding)

message(
  "Transcripts without a biotype (counted as non-protein-coding): ",
  sum(is.na(res_list$C3_vs_C0$biotype))
)

resp_iso <- bind_rows(
  get_significant_det(res_list$C3_vs_C0, "C3_vs_C0"),
  get_significant_det(res_list$C7_vs_C0, "C7_vs_C0")
) %>%
  mutate(contrast_pretty = factor(contrast_pretty, levels = comparison_levels))

write_csv(resp_iso, file.path(results_dir, "Fig2_significant_DETs_source_data.csv"))

# ==============================================================================
# Figure 2A: DET distribution by direction and protein-coding status
# ==============================================================================

det_diverging <- bind_rows(
  count_det_direction(res_list$C3_vs_C0, "C3 vs. C0"),
  count_det_direction(res_list$C7_vs_C0, "C7 vs. C0")
) %>%
  arrange(comparison, direction, transcript_class) %>%
  group_by(comparison, direction) %>%
  mutate(
    cum_upper = cumsum(n),
    cum_lower = cum_upper - n,
    ymin = if_else(direction == "Down", -cum_upper, cum_lower),
    ymax = if_else(direction == "Down", -cum_lower, cum_upper),
    label_y = (ymin + ymax) / 2
  ) %>%
  ungroup() %>%
  mutate(
    x_num = as.numeric(comparison),
    xmin = x_num - bar_half_width,
    xmax = x_num + bar_half_width
  ) %>%
  dplyr::select(-cum_upper, -cum_lower)

max_val <- max(det_diverging$ymax)
min_val <- min(det_diverging$ymin)

p_det_bars <- ggplot(det_diverging) +
  geom_rect(
    aes(
      xmin = xmin,
      xmax = xmax,
      ymin = ymin,
      ymax = ymax,
      fill = comparison,
      alpha = transcript_class
    ),
    color = "black",
    linewidth = 0.2
  ) +
  geom_text(aes(x = x_num, y = label_y, label = n), size = 2, color = "black") +
  geom_hline(yintercept = 0, linewidth = 0.2, linetype = "dashed") +
  scale_x_continuous(breaks = seq_along(comparison_levels), labels = comparison_levels) +
  scale_y_continuous(
    limits = c(min_val, max_val),
    breaks = c(min_val * 0.6, 0, max_val * 0.6),
    labels = c("Decrease", "", "Increase")
  ) +
  scale_fill_manual(values = comparison_colors, guide = "none") +
  scale_alpha_manual(values = transcript_class_alpha, guide = "none") +
  coord_cartesian(xlim = c(0.5, length(comparison_levels) + 0.5)) +
  labs(x = NULL, y = NULL, title = "DET Distribution") +
  theme_pub() +
  theme(
    axis.text.x = element_text(size = 6),
    axis.text.y = element_text(size = 6, angle = 90, hjust = 0.5),
    plot.margin = margin(t = 8, r = 2, b = 2, l = 4, unit = "mm")
  )

# Custom legend with one swatch per comparison color for each coding class.
legend_boxes <- tibble(
  x = c(1, 2, 7, 8),
  fill = rep(unname(comparison_colors[comparison_levels]), times = 2),
  alpha = rep(unname(transcript_class_alpha), each = 2)
)

legend_labels <- tibble(
  x = c(2.7, 8.7),
  label = c("Coding", "Non-coding")
)

p_det_legend <- ggplot() +
  geom_tile(
    data = legend_boxes,
    aes(x = x, y = 1, fill = I(fill), alpha = I(alpha)),
    color = "black",
    linewidth = 0.2,
    width = 0.8,
    height = 0.8
  ) +
  geom_text(data = legend_labels, aes(x = x, y = 1, label = label), hjust = 0, size = 2) +
  coord_fixed(ratio = 1, xlim = c(0, 15), ylim = c(0.4, 1.6), clip = "off") +
  theme_void(base_size = 7)

p_det_distribution <- p_det_bars / p_det_legend + plot_layout(heights = c(1, 0.08))

save_panel(p_det_distribution, "Fig2A_DET_Distribution.png", width_mm = 45, height_mm = 65)
write_csv(
  det_diverging %>% dplyr::select(comparison, direction, transcript_class, n),
  file.path(results_dir, "Fig2A_DET_distribution_source_data.csv")
)

# Significant non-protein-coding DETs with DESeq2 statistics
noncoding_dets <- bind_rows(
  get_noncoding_dets(res_list$C3_vs_C0, "C3 vs. C0"),
  get_noncoding_dets(res_list$C7_vs_C0, "C7 vs. C0")
)

write_csv(
  noncoding_dets,
  file.path(results_dir, "Fig2A_NonProteinCoding_Significant_DETs.csv")
)

write_csv(
  noncoding_dets %>%
    dplyr::count(comparison, biotype, direction, name = "n_transcripts", sort = TRUE),
  file.path(results_dir, "Fig2A_NonProteinCoding_DET_biotype_summary.csv")
)

# ==============================================================================
# Figure 2B: Genes with multiple DETs
# ==============================================================================

multi_det_gene_table <- resp_iso %>%
  dplyr::count(contrast_pretty, gene_symbol, name = "n_det_isoforms") %>%
  mutate(
    det_gene_class = if_else(n_det_isoforms >= 2, "≥2 DETs", "1 DET"),
    det_gene_class = factor(det_gene_class, levels = c("≥2 DETs", "1 DET"))
  )

multi_det_genes <- multi_det_gene_table %>%
  filter(det_gene_class == "≥2 DETs") %>%
  dplyr::select(gene_symbol, contrast_pretty)

multi_det_plot_df <- multi_det_gene_table %>%
  dplyr::count(contrast_pretty, det_gene_class) %>%
  group_by(contrast_pretty) %>%
  mutate(frac = n / sum(n)) %>%
  ungroup()

p_multi_det_genes <- plot_stacked_percent(
  plot_df = multi_det_plot_df,
  x_var = contrast_pretty,
  fill_var = det_gene_class,
  y_lab = "Percentage of DET-associated genes",
  title = "Genes with Multiple DETs"
)

save_panel(p_multi_det_genes, "Fig2B_MultiDET_Genes.png", width_mm = 50, height_mm = 65)
write_csv(multi_det_genes, file.path(results_dir, "DET_multi.csv"))
write_csv(multi_det_plot_df, file.path(results_dir, "Fig2B_MultiDET_genes_source_data.csv"))

# ==============================================================================
# Figure 2C: GO enrichment of multi-DET genes (C3 and C7)
# ==============================================================================

# Background: genes with >= 2 isoforms in the filtered isoform set tested by
# DESeq2. Single-isoform genes cannot have multiple DETs and are excluded.
# Isoforms are counted per Ensembl gene ID; isoforms without one are assigned
# the Ensembl ID of their gene symbol where available.
gene_id_map <- read_tsv(count_path, show_col_types = FALSE) %>%
  filter(
    !is.na(gene_symbol),
    !is.na(associated_gene),
    str_starts(associated_gene, "ENSMUSG")
  ) %>%
  distinct(gene_symbol, mapped_associated_gene = associated_gene)

mono_isoform_genes <- res_list$C3_vs_C0 %>%
  left_join(gene_id_map, by = "gene_symbol", relationship = "many-to-many") %>%
  mutate(
    associated_gene = case_when(
      !is.na(associated_gene) & str_starts(associated_gene, "ENSMUSG") ~ associated_gene,
      !is.na(mapped_associated_gene) ~ mapped_associated_gene,
      TRUE ~ NA_character_
    )
  ) %>%
  filter(!is.na(associated_gene), !is.na(transcript_id)) %>%
  distinct(associated_gene, transcript_id) %>%
  dplyr::count(associated_gene, name = "n_isoforms") %>%
  filter(n_isoforms == 1) %>%
  pull(associated_gene)

multi_isoform_genes <- res_list$C3_vs_C0 %>%
  filter(!associated_gene %in% mono_isoform_genes, !is.na(gene_symbol)) %>%
  pull(gene_symbol) %>%
  unique()

message("GO background (multi-isoform genes): ", length(multi_isoform_genes))

run_multi_det_go <- function(target_contrast_pretty) {
  target_genes <- multi_det_genes %>%
    filter(contrast_pretty == target_contrast_pretty) %>%
    distinct(gene_symbol) %>%
    pull(gene_symbol)

  ego <- enrichGO(
    gene = to_entrez(target_genes),
    universe = to_entrez(multi_isoform_genes),
    OrgDb = org.Mm.eg.db,
    keyType = "ENTREZID",
    ont = go_ontology,
    pAdjustMethod = "BH",
    pvalueCutoff = padj_cutoff,
    qvalueCutoff = padj_cutoff,
    readable = TRUE
  )

  simplify(ego, cutoff = go_simplify_cutoff, by = "p.adjust", select_fun = min)@result %>%
    arrange(p.adjust) %>%
    slice_head(n = go_top_n)
}

plot_go_dot_from_df <- function(plot_df, title, dot_color, fdr_max = padj_cutoff) {
  df <- plot_df %>%
    filter(p.adjust <= fdr_max) %>%
    mutate(
      gene_ratio_num = parse_gene_ratio(GeneRatio),
      Description = str_wrap(Description, width = 30),
      neglog10_fdr = -log10(p.adjust + 1e-300)
    ) %>%
    arrange(Count) %>%
    mutate(Description = factor(Description, levels = unique(Description)))

  ggplot(df, aes(x = gene_ratio_num, y = Description)) +
    geom_point(aes(size = Count, color = neglog10_fdr)) +
    scale_size(range = c(0.8, 3), breaks = pretty_breaks(n = 4)) +
    scale_color_gradient(low = "grey30", high = dot_color, breaks = pretty_breaks(n = 4)) +
    labs(
      title = title,
      x = "Gene Ratio",
      y = NULL,
      color = expression(-log[10]("adj. P")),
      size = "\nCount"
    ) +
    theme_minimal(base_size = 7) +
    theme(
      panel.grid.minor = element_blank(),
      axis.line = element_line(color = "black", linewidth = 0.3),
      axis.ticks = element_line(color = "black", linewidth = 0.3),
      axis.ticks.length = unit(0.15, "cm"),
      plot.title = element_text(size = 7, face = "bold", hjust = 0.5),
      axis.text.x = element_text(size = 5),
      axis.text.y = element_text(size = 5),
      axis.title = element_text(size = 5),
      legend.title = element_text(size = 4),
      legend.text = element_text(size = 4),
      legend.key.height = unit(0.35, "cm"),
      legend.key.width = unit(0.2, "cm"),
      legend.spacing.y = unit(0.1, "cm")
    ) +
    guides(
      color = guide_colorbar(order = 1, barheight = unit(1.5, "cm"), barwidth = unit(0.25, "cm")),
      size = guide_legend(order = 2, keyheight = unit(0.35, "cm"), keywidth = unit(0.35, "cm"))
    )
}

for (comparison in comparison_levels) {
  timepoint <- str_extract(comparison, "^C\\d+")

  go_df <- run_multi_det_go(comparison)

  p_go <- plot_go_dot_from_df(
    plot_df = go_df,
    title = paste0("GO: ", timepoint, " Multi-DET Genes"),
    dot_color = comparison_colors[[comparison]]
  )

  save_panel(
    p_go,
    paste0("Fig2C_", timepoint, "_MultiDET_GO.png"),
    width_mm = 62,
    height_mm = 55
  )

  write_csv(
    go_df,
    file.path(results_dir, paste0("Fig2C_", timepoint, "_MultiDET_GO_source_data.csv"))
  )
}

# ==============================================================================
# Figure 2D: Emergence categories of DETs
# ==============================================================================

c0_cols <- names(counts_filtered)[str_detect(names(counts_filtered), "^C0")]
if (length(c0_cols) == 0) stop("No C0 columns detected in counts table.")

baseline_tbl <- get_baseline_status(counts_filtered, c0_cols, min_count, min_reps) %>%
  dplyr::select(
    transcript_id,
    transcript_symbol,
    gene_symbol,
    n_C0_ge_min,
    iso_expressed_baseline,
    gene_has_any_baseline_isoform,
    baseline_status
  ) %>%
  distinct(transcript_id, .keep_all = TRUE)

det_annot <- resp_iso %>%
  left_join(baseline_tbl, by = c("transcript_symbol", "gene_symbol", "transcript_id")) %>%
  mutate(
    baseline_status = factor(
      baseline_status,
      levels = c("Emerged: Remodeling", "Emerged: Activation", "Expressed at Baseline")
    )
  )

if (any(is.na(det_annot$baseline_status))) {
  warning(sum(is.na(det_annot$baseline_status)), " DETs have no baseline status.")
}

emergence_plot_df <- det_annot %>%
  dplyr::count(contrast_pretty, baseline_status) %>%
  group_by(contrast_pretty) %>%
  mutate(frac = n / sum(n)) %>%
  ungroup()

p_emergence <- plot_stacked_percent(
  plot_df = emergence_plot_df,
  x_var = contrast_pretty,
  fill_var = baseline_status,
  y_lab = "Percentage of DETs",
  title = "Emergence of DETs"
) +
  scale_fill_discrete(labels = function(x) str_wrap(x, width = 18))

save_panel(p_emergence, "Fig2D_DET_Emergence.png", width_mm = 52, height_mm = 65)
write_csv(det_annot, file.path(results_dir, "Fig2D_DET_emergence_annotated_source_data.csv"))
write_csv(emergence_plot_df, file.path(results_dir, "Fig2D_DET_emergence_plot_source_data.csv"))

det_emerge_remodel <- det_annot %>%
  filter(baseline_status == "Emerged: Remodeling") %>%
  dplyr::select(transcript_symbol, gene_symbol, contrast_pretty)

det_emerge_activation <- det_annot %>%
  filter(baseline_status == "Emerged: Activation") %>%
  dplyr::select(transcript_symbol, gene_symbol, contrast_pretty)

write_csv(det_emerge_remodel, file.path(results_dir, "DET_emerged_remodeling.csv"))
write_csv(det_emerge_activation, file.path(results_dir, "DET_emerged_activation.csv"))

# ==============================================================================
# Figure 2E: Structural remodeling among emerged-remodeling DETs
# ==============================================================================

counts_for_structure <- counts_filtered %>% dplyr::rename(tx_id = transcript_symbol)

count_long <- counts_for_structure %>%
  dplyr::select(tx_id, starts_with("C0_"), starts_with("C3_"), starts_with("C7_")) %>%
  pivot_longer(-tx_id, names_to = "sample", values_to = "count") %>%
  mutate(
    sample = standardize_sample_name(sample),
    condition = str_extract(sample, "^C\\d+")
  ) %>%
  left_join(counts_for_structure %>% distinct(tx_id, gene_symbol), by = "tx_id")

baseline_tbl_structure <- get_baseline_status(counts_for_structure, c0_cols, min_count, min_reps) %>%
  dplyr::select(tx_id, gene_symbol, n_C0_ge_min, iso_expressed_baseline, gene_has_any_baseline_isoform, baseline_status) %>%
  distinct(tx_id, .keep_all = TRUE)

c0_dominant_isoform <- count_long %>%
  filter(condition == "C0", !is.na(gene_symbol)) %>%
  group_by(gene_symbol, tx_id) %>%
  summarise(mean_count_C0 = mean(count, na.rm = TRUE), .groups = "drop") %>%
  left_join(
    baseline_tbl_structure %>% distinct(tx_id, gene_symbol, iso_expressed_baseline),
    by = c("tx_id", "gene_symbol")
  ) %>%
  filter(iso_expressed_baseline) %>%
  group_by(gene_symbol) %>%
  slice_max(mean_count_C0, n = 1, with_ties = FALSE) %>%
  ungroup() %>%
  dplyr::rename(ref_tx = tx_id)

tx_keep <- det_emerge_remodel %>%
  mutate(tx_id = transcript_symbol) %>%
  pull(tx_id) %>%
  union(c0_dominant_isoform$ref_tx) %>%
  unique() %>%
  na.omit()

known_tx_keep <- tx_keep[!str_detect(tx_keep, "novel")]
novel_tx_keep <- tx_keep[str_detect(tx_keep, "novel")]

# ---- Known transcript structure from Ensembl reference GTF --------------------
known_structure <- ref_gtf %>%
  mutate(transcript_name = if_else(is.na(transcript_name), transcript_id, transcript_name)) %>%
  filter(transcript_name %in% known_tx_keep, type %in% c("CDS", "five_prime_utr", "three_prime_utr")) %>%
  transmute(
    tx_id = transcript_name,
    gene_name,
    seqnames,
    start,
    end,
    strand,
    region_type = if_else(type == "CDS", "CDS", "UTR"),
    source = "Ensembl_reference",
    transcript_id
  ) %>%
  distinct()

# ---- Novel transcript ORF boundaries from SQANTI3 classifications -------------
orf_sqanti <- map_dfr(sqanti_class_files, ~ read_tsv(.x, show_col_types = FALSE)) %>%
  transmute(
    transcript_id,
    strand,
    coding,
    CDS_genomic_start_raw = suppressWarnings(as.numeric(CDS_genomic_start)),
    CDS_genomic_end_raw = suppressWarnings(as.numeric(CDS_genomic_end)),
    cds_len = abs(CDS_genomic_end_raw - CDS_genomic_start_raw)
  ) %>%
  group_by(transcript_id) %>%
  arrange(dplyr::desc(replace_na(cds_len, -Inf)), .by_group = TRUE) %>%
  dplyr::slice(1) %>%
  ungroup() %>%
  transmute(
    transcript_id,
    strand,
    coding,
    CDS_genomic_start = CDS_genomic_start_raw,
    CDS_genomic_end = CDS_genomic_end_raw
  ) %>%
  distinct()

# ---- Novel transcript exon and CDS coordinates from renamed GTF files ----------
gtf_all <- map_dfr(renamed_gtf_files, function(f) {
  rtracklayer::import(f) %>%
    as.data.frame() %>%
    filter(transcript_id %in% tx_keep) %>%
    mutate(sample = str_remove(basename(f), "\\.gtf$"))
})

cds_from_gtf <- gtf_all %>%
  filter(type == "CDS") %>%
  group_by(transcript_id) %>%
  summarise(
    CDS_genomic_start = min(start),
    CDS_genomic_end = max(end),
    .groups = "drop"
  )

orf_combined <- full_join(orf_sqanti, cds_from_gtf, by = "transcript_id") %>%
  transmute(
    transcript_id,
    coding,
    CDS_genomic_start = coalesce(CDS_genomic_start.x, CDS_genomic_start.y),
    CDS_genomic_end = coalesce(CDS_genomic_end.x, CDS_genomic_end.y)
  )

gtf_exons <- gtf_all %>%
  filter(type == "exon") %>%
  left_join(orf_combined, by = "transcript_id")

novel_selected <- gtf_exons %>%
  filter(transcript_id %in% novel_tx_keep) %>%
  arrange(transcript_id, start) %>%
  distinct(
    seqnames,
    start,
    end,
    strand,
    transcript_id,
    gene_id,
    coding,
    CDS_genomic_start,
    CDS_genomic_end,
    .keep_all = TRUE
  )

novel_structure <- novel_selected %>%
  rowwise() %>%
  do(split_exon_by_orf(.)) %>%
  ungroup() %>%
  mutate(
    tx_id = transcript_id,
    coding_class = coding,
    region_type = case_when(
      region_type == "CDS" ~ "CDS",
      region_type %in% c("5UTR", "3UTR", "UTR") ~ "UTR",
      TRUE ~ NA_character_
    ),
    source = "SQANTI3_ORF_prediction"
  ) %>%
  dplyr::select(tx_id, seqnames, start, end, strand, coding_class, region_type, source) %>%
  filter(!is.na(region_type)) %>%
  distinct()

tx_structure_all <- bind_rows(
  known_structure %>% dplyr::select(tx_id, seqnames, start, end, strand, region_type, source),
  novel_structure %>% dplyr::select(tx_id, seqnames, start, end, strand, region_type, source)
) %>%
  filter(!is.na(region_type)) %>%
  distinct()

isoform_structure_input <- det_emerge_remodel %>%
  mutate(tx_id = transcript_symbol) %>%
  left_join(
    baseline_tbl_structure %>% dplyr::select(tx_id, gene_symbol, iso_expressed_baseline, baseline_status),
    by = c("tx_id", "gene_symbol")
  ) %>%
  left_join(c0_dominant_isoform, by = "gene_symbol") %>%
  filter(!is.na(ref_tx), tx_id != ref_tx)

# Each DET is compared against the dominant baseline isoform of its gene.
compare_df <- isoform_structure_input %>%
  distinct(tx_id, ref_tx) %>%
  mutate(compare = map2(tx_id, ref_tx, ~ compare_tx_to_ref(.x, .y, tx_structure_all))) %>%
  dplyr::select(compare) %>%
  unnest(compare)

isoform_structure_gr <- isoform_structure_input %>%
  left_join(compare_df, by = c("tx_id", "ref_tx"))

# ---- Coding class annotation --------------------------------------------------
known_coding_by_cds <- ref_gtf %>%
  mutate(transcript_name = if_else(is.na(transcript_name), transcript_id, transcript_name)) %>%
  filter(transcript_name %in% known_tx_keep) %>%
  group_by(transcript_name) %>%
  summarise(
    has_CDS = any(type == "CDS"),
    transcript_biotype = dplyr::first(na.omit(transcript_biotype)),
    .groups = "drop"
  ) %>%
  mutate(
    tx_id = transcript_name,
    coding_class = if_else(has_CDS, "coding", "noncoding"),
    coding_source = "Ensembl_CDS_presence"
  ) %>%
  dplyr::select(tx_id, coding_class, coding_source, transcript_biotype, has_CDS)

novel_biotype <- orf_combined %>%
  filter(transcript_id %in% novel_tx_keep) %>%
  mutate(
    tx_id = transcript_id,
    has_predicted_orf = !is.na(CDS_genomic_start) & !is.na(CDS_genomic_end),
    coding_class = if_else(coding == "coding", "coding", "noncoding"),
    coding_source = "SQANTI3_ORF_prediction",
    transcript_biotype = if_else(has_predicted_orf, "predicted_protein_coding", "predicted_noncoding")
  ) %>%
  dplyr::select(tx_id, coding_class, coding_source, transcript_biotype)

tx_coding_annot <- bind_rows(known_coding_by_cds, novel_biotype) %>%
  distinct(tx_id, .keep_all = TRUE)

isoform_structure_gr <- isoform_structure_gr %>%
  left_join(
    tx_coding_annot %>%
      dplyr::rename(
        tx_coding_class = coding_class,
        tx_coding_source = coding_source,
        tx_biotype = transcript_biotype
      ),
    by = "tx_id"
  ) %>%
  left_join(
    tx_coding_annot %>%
      dplyr::rename(
        ref_tx = tx_id,
        ref_coding_class = coding_class,
        ref_coding_source = coding_source,
        ref_biotype = transcript_biotype
      ),
    by = "ref_tx"
  ) %>%
  mutate(
    coding_transition = case_when(
      ref_coding_class == "coding" & tx_coding_class == "coding" ~ "coding_to_coding",
      ref_coding_class == "coding" & tx_coding_class == "noncoding" ~ "coding_to_noncoding",
      ref_coding_class == "noncoding" & tx_coding_class == "coding" ~ "noncoding_to_coding",
      ref_coding_class == "noncoding" & tx_coding_class == "noncoding" ~ "noncoding_to_noncoding",
      TRUE ~ "unknown"
    ),
    comparison_type = case_when(
      !str_detect(tx_id, "novel") & !str_detect(ref_tx, "novel") ~ "known_vs_known",
      str_detect(tx_id, "novel") & !str_detect(ref_tx, "novel") ~ "novel_vs_known",
      !str_detect(tx_id, "novel") & str_detect(ref_tx, "novel") ~ "known_vs_novel",
      str_detect(tx_id, "novel") & str_detect(ref_tx, "novel") ~ "novel_vs_novel",
      TRUE ~ "unknown"
    ),
    final_class = case_when(
      structure_change_class == "UTR only" ~ "UTR Only",
      str_starts(structure_change_class, "CDS") ~ "ORF Modification",
      structure_change_class == "Coding-Noncoding Switch" & coding_transition == "noncoding_to_coding" ~ "ORF Gain",
      structure_change_class == "Coding-Noncoding Switch" & coding_transition == "coding_to_noncoding" ~ "ORF Loss",
      structure_change_class == "Coding-Noncoding Switch" & coding_transition == "noncoding_to_noncoding" ~ "Noncoding",
      TRUE ~ "unknown"
    )
  )

write_csv(isoform_structure_gr, file.path(results_dir, "Fig2E_isoform_structure_comparison_source_data.csv"))

remodel_plot_df <- isoform_structure_gr %>%
  filter(final_class %in% remodel_class_levels) %>%
  dplyr::count(contrast_pretty, final_class, name = "n_isoforms") %>%
  complete(
    contrast_pretty = comparison_levels,
    final_class = remodel_class_levels,
    fill = list(n_isoforms = 0)
  ) %>%
  group_by(contrast_pretty) %>%
  mutate(value = 100 * n_isoforms / sum(n_isoforms)) %>%
  ungroup() %>%
  mutate(
    contrast_pretty = factor(contrast_pretty, levels = comparison_levels),
    final_class = factor(final_class, levels = remodel_class_levels)
  )

p_remodeling <- ggplot(remodel_plot_df, aes(x = contrast_pretty, y = value, fill = final_class)) +
  geom_col(width = 0.9, color = "black", linewidth = 0.25) +
  geom_text(aes(label = pct_lab_value(value)), position = position_stack(vjust = 0.5), size = 1.6) +
  scale_y_continuous(expand = c(0, 0), labels = function(x) paste0(x, "%"), position = "right") +
  coord_cartesian(ylim = c(0, 100)) +
  scale_fill_discrete(palette = "Set2", labels = function(x) str_wrap(x, width = 18)) +
  labs(x = NULL, y = NULL, title = "Remodeling of DETs", fill = NULL) +
  theme_pub() +
  theme(
    legend.position = "bottom",
    legend.box = "horizontal",
    legend.key.size = unit(2, "mm"),
    legend.text = element_text(size = 5),
    legend.spacing.y = unit(1, "mm"),
    legend.spacing.x = unit(1, "mm"),
    legend.box.margin = margin(t = -2, r = -4, b = 0, l = 0, unit = "mm")
  ) +
  guides(fill = guide_legend(nrow = 2, byrow = FALSE))

save_panel(p_remodeling, "Fig2E_UTR_CDS_ORF_Remodeling.png", width_mm = 50, height_mm = 68)
write_csv(remodel_plot_df, file.path(results_dir, "Fig2E_UTR_CDS_ORF_remodeling_plot_source_data.csv"))

message("Figure 2 plotting complete. Figures saved to: ", figure_dir)
