#!/usr/bin/env Rscript

################################################################################
# Figure 2: Peripheral nerve injury induces widespread isoform remodeling with 
#  distinct modes of transcript emergence and functional consequences.
#
# Panels generated by this script:
#   A: DET distribution by direction, split by protein-coding status
#   B: Genes with single versus multiple DETs
#   C: GO enrichment of multi-DET genes (background: multi-isoform genes)
#   D: Emergence categories of DETs
#   E: Structural remodeling categories among emerged-remodeling DETs
#
# Panels F - H are generated using:
#     Plotting_isoform_expression.R
#     Plotting_isoform_proportion.R
#     Plotting_isoform_trackplot.R
#
# Notes:
#   DESeq2 for DTE analysis are performed in:
#      Isoform_Analysis/DTE_Analysis_DESeq2.R
#   DET emergence and structural remodeling classification are performed in:
#     Isoform_Analysis/DET_Remodeling_Classification.R
#   Transcript biotypes are taken from the Ensembl reference GTF (known
#   transcripts) and SQANTI3 ORF predictions (novel transcripts).
#
################################################################################

suppressPackageStartupMessages({
  library(tidyverse)
  library(clusterProfiler)
  library(org.Mm.eg.db)
  library(rtracklayer)
  library(patchwork)
  library(scales)
  library(grid)
})

# ==============================================================================
# User-defined files/directories
# ==============================================================================

isoform_results_dir <- "/path/to/isoform_analysis_results"       # <-- MODIFY HERE
det_classification_dir <- file.path(
  isoform_results_dir,
  "DET_Remodeling_Classification"
)                                                                # <-- MODIFY HERE IF NEEDED

ref_gtf_path <- "/path/to/Mus_musculus.GRCm39.115.chr.gtf"       # <-- MODIFY HERE

sqanti_class_dir <- "/path/to/SQANTI3_classification_files"      # <-- MODIFY HERE
sqanti_class_pattern <- "classification.*\\.txt$"                # <-- MODIFY HERE IF NEEDED

figure_dir <- "/path/to/Figure_2_output"                         # <-- MODIFY HERE

dir.create(figure_dir, recursive = TRUE, showWarnings = FALSE)

# ==============================================================================
# Input files
# ==============================================================================

res_c3_path <- file.path(
  isoform_results_dir,
  "C3_vs_C0_isoform_results.csv"
)                                                                # <-- MODIFY HERE IF NEEDED

res_c7_path <- file.path(
  isoform_results_dir,
  "C7_vs_C0_isoform_results.csv"
)                                                                # <-- MODIFY HERE IF NEEDED

det_emergence_path <- file.path(
  det_classification_dir,
  "DET_emergence_classification.csv"
)                                                                # <-- MODIFY HERE IF NEEDED

det_structural_path <- file.path(
  det_classification_dir,
  "DET_structural_remodeling_classification.csv"
)                                                                # <-- MODIFY HERE IF NEEDED

required_files <- c(
  res_c3_path,
  res_c7_path,
  ref_gtf_path,
  det_emergence_path,
  det_structural_path
)

missing_files <- required_files[!file.exists(required_files)]

if (length(missing_files) > 0) {
  stop(
    "Missing required file(s):\n",
    paste(missing_files, collapse = "\n"),
    call. = FALSE
  )
}

sqanti_class_files <- list.files(
  sqanti_class_dir,
  pattern = sqanti_class_pattern,
  full.names = TRUE
)

if (length(sqanti_class_files) == 0) {
  stop("No SQANTI3 classification files found in: ", sqanti_class_dir, call. = FALSE)
}

# ==============================================================================
# Parameters
# ==============================================================================

padj_cutoff <- 0.05                                               # <-- MODIFY HERE IF NEEDED
lfc_cutoff <- 1                                                   # <-- MODIFY HERE IF NEEDED

comparison_levels <- c("C3 vs. C0", "C7 vs. C0")

comparison_colors <- c(
  "C3 vs. C0" = "#E69F00",
  "C7 vs. C0" = "#66BD63"
)

# Transcript biotypes counted as protein-coding in Figure 2A. Novel isoforms
# are labeled "novel_coding" / "novel_non_coding" from SQANTI3 ORF predictions.
coding_biotypes <- c(
  "protein_coding",
  "protein_coding_CDS_not_defined",
  "novel_coding"
)                                                                 # <-- MODIFY HERE IF NEEDED

transcript_class_levels <- c("Protein-coding", "Non-protein-coding")

transcript_class_alpha <- c(
  "Protein-coding" = 1,
  "Non-protein-coding" = 0.3
)

bar_half_width <- 0.42                                            # <-- MODIFY HERE IF NEEDED

remodel_class_levels <- c(
  "UTR Only",
  "Noncoding",
  "ORF Loss",
  "ORF Gain",
  "ORF Modification"
)

# ==============================================================================
# Helper functions
# ==============================================================================

theme_pub <- function(base_size = 7) {
  theme_classic(base_size = base_size) +
    theme(
      axis.line = element_line(color = "black", linewidth = 0.3),
      axis.ticks = element_line(color = "black", linewidth = 0.3),
      axis.ticks.length = unit(0.15, "cm"),
      panel.grid = element_blank(),
      axis.text.x = element_text(size = 5, hjust = 0.5, vjust = 0.5),
      axis.text.y = element_text(size = 5),
      axis.title.x = element_text(size = 6, margin = margin(t = 3)),
      axis.title.y = element_text(size = 6, margin = margin(r = 3)),
      plot.title = element_text(
        size = 7,
        face = "bold",
        hjust = 0.5,
        margin = margin(b = 4)
      ),
      legend.key.size = unit(3, "mm"),
      legend.text = element_text(size = 5),
      legend.title = element_blank(),
      plot.margin = margin(t = 8, r = 4, b = 4, l = 4, unit = "mm")
    )
}

save_panel <- function(plot, filename, width_mm, height_mm) {
  ggsave(
    filename = file.path(figure_dir, filename),
    plot = plot,
    width = width_mm,
    height = height_mm,
    units = "mm",
    dpi = 600,
    bg = "white"
  )
}

pct_lab_frac <- function(x) sprintf("%.1f%%", 100 * x)
pct_lab_value <- function(x) sprintf("%.1f%%", x)

recode_contrast <- function(x) {
  dplyr::recode(
    x,
    "C3_vs_C0" = "C3 vs. C0",
    "C7_vs_C0" = "C7 vs. C0"
  )
}

strip_ensembl_version <- function(x) {
  if_else(str_starts(x, "ENSMUS"), str_remove(x, "\\.\\d+$"), x)
}

filter_dets <- function(res) {
  res %>%
    filter(!is.na(padj), padj <= padj_cutoff, abs(log2FoldChange) >= lfc_cutoff)
}

# Adds `biotype` and `transcript_class` (Protein-coding / Non-protein-coding).
# Known transcripts use the reference GTF biotype; novel transcripts, which have
# no reference biotype, use the SQANTI3 coding prediction.
annotate_transcript_class <- function(res, known_biotype, novel_coding) {
  res %>%
    mutate(join_id = strip_ensembl_version(transcript_id)) %>%
    left_join(known_biotype, by = c("join_id" = "transcript_id")) %>%
    left_join(novel_coding, by = c("join_id" = "transcript_id")) %>%
    mutate(
      biotype = case_when(
        !is.na(biotype) ~ biotype,
        coding == "coding" ~ "novel_coding",
        coding == "non_coding" ~ "novel_non_coding",
        TRUE ~ NA_character_
      ),
      transcript_class = factor(
        if_else(
          !is.na(biotype) & biotype %in% coding_biotypes,
          "Protein-coding",
          "Non-protein-coding"
        ),
        levels = transcript_class_levels
      )
    ) %>%
    dplyr::select(-join_id, -coding)
}

count_det_direction <- function(res, comparison_label) {
  filter_dets(res) %>%
    mutate(direction = if_else(log2FoldChange > 0, "Up", "Down")) %>%
    count(direction, transcript_class) %>%
    mutate(comparison = factor(comparison_label, levels = comparison_levels))
}

get_noncoding_dets <- function(res, comparison_label) {
  filter_dets(res) %>%
    filter(transcript_class == "Non-protein-coding") %>%
    mutate(
      direction = if_else(log2FoldChange > 0, "Increase", "Decrease"),
      comparison = comparison_label
    ) %>%
    dplyr::select(
      transcript_id,
      transcript_symbol,
      gene_symbol,
      biotype,
      direction,
      comparison,
      baseMean,
      log2FoldChange,
      lfcSE,
      stat,
      pvalue,
      padj
    ) %>%
    arrange(padj, dplyr::desc(abs(log2FoldChange)))
}

to_entrez <- function(symbols) {
  suppressMessages(
    clusterProfiler::bitr(
      unique(symbols),
      fromType = "SYMBOL",
      toType = "ENTREZID",
      OrgDb = org.Mm.eg.db
    )
  ) %>%
    pull(ENTREZID) %>%
    unique()
}

parse_gene_ratio <- function(x) {
  purrr::map_dbl(x, function(ratio) {
    parts <- str_split(ratio, "/", simplify = TRUE)
    as.numeric(parts[1]) / as.numeric(parts[2])
  })
}

plot_stacked_percent <- function(plot_df, x_var, fill_var, y_lab, title) {
  ggplot(plot_df, aes(x = {{ x_var }}, y = frac, fill = {{ fill_var }})) +
    geom_col(width = 0.9, color = "black", linewidth = 0.25) +
    geom_text(
      aes(label = pct_lab_frac(frac)),
      position = position_stack(vjust = 0.5),
      size = 2
    ) +
    scale_y_continuous(
      labels = scales::percent_format(accuracy = 1),
      expand = c(0, 0)
    ) +
    labs(
      x = NULL,
      y = y_lab,
      title = title,
      fill = NULL
    ) +
    theme_pub() +
    theme(
      legend.position = "bottom",
      legend.box = "horizontal",
      legend.text = element_text(size = 6),
      legend.spacing.y = unit(1, "mm"),
      legend.spacing.x = unit(1, "mm"),
      legend.box.margin = margin(t = -2, r = 0, b = 0, l = 0, unit = "mm")
    )
}

# ==============================================================================
# Load data
# ==============================================================================

res_c3 <- readr::read_csv(res_c3_path, show_col_types = FALSE)
res_c7 <- readr::read_csv(res_c7_path, show_col_types = FALSE)

det_emergence <- readr::read_csv(det_emergence_path, show_col_types = FALSE)
det_structural <- readr::read_csv(det_structural_path, show_col_types = FALSE)

# ==============================================================================
# Annotate transcript coding status
# ==============================================================================

message("Importing reference GTF: ", ref_gtf_path)

known_biotype <- rtracklayer::import(ref_gtf_path) %>%
  as.data.frame() %>%
  filter(type == "transcript") %>%
  transmute(
    transcript_id = strip_ensembl_version(transcript_id),
    biotype = transcript_biotype
  ) %>%
  distinct(transcript_id, .keep_all = TRUE)

# One coding call per novel transcript: the most frequent call across samples.
novel_coding <- purrr::map_dfr(
  sqanti_class_files,
  ~ readr::read_tsv(.x, show_col_types = FALSE) %>%
    filter(filter_rescued_result == "Isoform") %>%
    dplyr::select(transcript_id, coding)
) %>%
  count(transcript_id, coding) %>%
  group_by(transcript_id) %>%
  slice_max(n, n = 1, with_ties = FALSE) %>%
  ungroup() %>%
  dplyr::select(transcript_id, coding)

res_c3 <- annotate_transcript_class(res_c3, known_biotype, novel_coding)
res_c7 <- annotate_transcript_class(res_c7, known_biotype, novel_coding)

message(
  "Transcripts without a biotype (counted as non-protein-coding): ",
  sum(is.na(res_c3$biotype))
)

# ==============================================================================
# Figure 2A: DET distribution by direction and protein-coding status
# ==============================================================================

det_diverging <- bind_rows(
  count_det_direction(res_c3, "C3 vs. C0"),
  count_det_direction(res_c7, "C7 vs. C0")
) %>%
  arrange(comparison, direction, transcript_class) %>%
  group_by(comparison, direction) %>%
  mutate(
    cum_upper = cumsum(n),
    cum_lower = cum_upper - n,
    ymin = if_else(direction == "Down", -cum_upper, cum_lower),
    ymax = if_else(direction == "Down", -cum_lower, cum_upper),
    label_y = (ymin + ymax) / 2
  ) %>%
  ungroup() %>%
  mutate(
    x_num = as.numeric(comparison),
    xmin = x_num - bar_half_width,
    xmax = x_num + bar_half_width
  ) %>%
  dplyr::select(-cum_upper, -cum_lower)

max_val <- max(det_diverging$ymax)
min_val <- min(det_diverging$ymin)

p_det_bars <- ggplot(det_diverging) +
  geom_rect(
    aes(
      xmin = xmin,
      xmax = xmax,
      ymin = ymin,
      ymax = ymax,
      fill = comparison,
      alpha = transcript_class
    ),
    color = "black",
    linewidth = 0.2
  ) +
  geom_text(
    aes(x = x_num, y = label_y, label = n),
    size = 2,
    color = "black"
  ) +
  geom_hline(yintercept = 0, linewidth = 0.2, linetype = "dashed") +
  scale_x_continuous(
    breaks = seq_along(comparison_levels),
    labels = comparison_levels
  ) +
  scale_y_continuous(
    limits = c(min_val, max_val),
    breaks = c(min_val * 0.6, 0, max_val * 0.6),
    labels = c("Decrease", "", "Increase")
  ) +
  scale_fill_manual(values = comparison_colors, guide = "none") +
  scale_alpha_manual(values = transcript_class_alpha, guide = "none") +
  coord_cartesian(xlim = c(0.5, length(comparison_levels) + 0.5)) +
  labs(x = NULL, y = NULL, title = "DET Distribution") +
  theme_pub() +
  theme(
    axis.text.x = element_text(size = 6),
    axis.text.y = element_text(size = 6, angle = 90, hjust = 0.5),
    plot.margin = margin(t = 8, r = 2, b = 2, l = 4, unit = "mm")
  )


legend_boxes <- tibble(
  x = c(1, 2, 7, 8),
  fill = rep(unname(comparison_colors[comparison_levels]), times = 2),
  alpha = rep(unname(transcript_class_alpha), each = 2)
)

legend_labels <- tibble(
  x = c(2.7, 8.7),
  label = c("Coding", "Non-coding")
)

p_det_legend <- ggplot() +
  geom_tile(
    data = legend_boxes,
    aes(x = x, y = 1, fill = I(fill), alpha = I(alpha)),
    color = "black",
    linewidth = 0.2,
    width = 0.8,
    height = 0.8
  ) +
  geom_text(
    data = legend_labels,
    aes(x = x, y = 1, label = label),
    hjust = 0,
    size = 2
  ) +
  coord_fixed(ratio = 1, xlim = c(0, 15), ylim = c(0.4, 1.6), clip = "off") +
  theme_void(base_size = 7)

p_det_distribution <- p_det_bars / p_det_legend +
  plot_layout(heights = c(1, 0.08))

save_panel(
  p_det_distribution,
  "Fig2A_DET_Distribution.png",
  width_mm = 45,
  height_mm = 65
)


# ==============================================================================
# Figure 2B: Genes with multiple DETs
# ==============================================================================

significant_dets <- bind_rows(
  res_c3 %>% mutate(contrast = "C3_vs_C0"),
  res_c7 %>% mutate(contrast = "C7_vs_C0")
) %>%
  filter_dets() %>%
  mutate(
    contrast_pretty = factor(recode_contrast(contrast), levels = comparison_levels)
  ) %>%
  distinct(transcript_id, contrast, .keep_all = TRUE)

multi_det_gene_table <- significant_dets %>%
  count(contrast_pretty, gene_symbol, name = "n_det_isoforms") %>%
  mutate(
    det_gene_class = if_else(n_det_isoforms >= 2, "≥2 DETs", "1 DET"),
    det_gene_class = factor(det_gene_class, levels = c("≥2 DETs", "1 DET"))
  )

multi_det_genes <- multi_det_gene_table %>%
  filter(det_gene_class == "≥2 DETs") %>%
  dplyr::select(gene_symbol, contrast_pretty)

multi_det_plot_df <- multi_det_gene_table %>%
  count(contrast_pretty, det_gene_class) %>%
  group_by(contrast_pretty) %>%
  mutate(frac = n / sum(n)) %>%
  ungroup()

p_multi_det_genes <- plot_stacked_percent(
  plot_df = multi_det_plot_df,
  x_var = contrast_pretty,
  fill_var = det_gene_class,
  y_lab = "Percentage of DET-associated genes",
  title = "Genes with Multiple DETs"
)

save_panel(
  p_multi_det_genes,
  "Fig2B_MultiDET_Genes.png",
  width_mm = 50,
  height_mm = 65
)

readr::write_csv(
  multi_det_genes,
  file.path(figure_dir, "DET_multi.csv")
)

readr::write_csv(
  multi_det_plot_df,
  file.path(figure_dir, "Fig2B_MultiDET_genes_source_data.csv")
)

# ==============================================================================
# Figure 2C: GO enrichment of multi-DET genes
# ==============================================================================

# Background: genes with >= 2 isoforms in the filtered isoform set tested by
# DESeq2. Mono-isoform genes cannot have multiple DETs, so they are excluded
# from the universe. Both result tables contain the same tested isoforms, so
# the background is identical for C3 and C7.
multi_isoform_genes <- bind_rows(res_c3, res_c7) %>%
  filter(!is.na(gene_symbol)) %>%
  distinct(gene_symbol, transcript_id) %>%
  count(gene_symbol, name = "n_isoforms") %>%
  filter(n_isoforms >= 2) %>%
  pull(gene_symbol)

message("GO background (multi-isoform genes): ", length(multi_isoform_genes))

run_multi_det_go <- function(target_contrast_pretty, top_n = 8, simplify_cutoff = 0.6) {
  target_genes <- multi_det_genes %>%
    filter(contrast_pretty == target_contrast_pretty) %>%
    distinct(gene_symbol) %>%
    pull(gene_symbol)

  universe_genes <- multi_isoform_genes

  ego <- enrichGO(
    gene = to_entrez(target_genes),
    universe = to_entrez(universe_genes),
    OrgDb = org.Mm.eg.db,
    keyType = "ENTREZID",
    ont = "BP",
    pAdjustMethod = "BH",
    pvalueCutoff = padj_cutoff,
    qvalueCutoff = padj_cutoff,
    readable = TRUE
  )

  simplify(
    ego,
    cutoff = simplify_cutoff,
    by = "p.adjust",
    select_fun = min
  )@result %>%
    arrange(p.adjust) %>%
    slice_head(n = top_n)
}

plot_go_dot_from_df <- function(plot_df, title, dot_color, fdr_max = padj_cutoff) {
  df <- plot_df %>%
    filter(p.adjust <= fdr_max) %>%
    mutate(
      gene_ratio_num = parse_gene_ratio(GeneRatio),
      Description = str_wrap(Description, width = 30),
      neglog10_fdr = -log10(p.adjust + 1e-300)
    ) %>%
    arrange(Count) %>%
    mutate(Description = factor(Description, levels = unique(Description)))

  ggplot(df, aes(x = gene_ratio_num, y = Description)) +
    geom_point(aes(size = Count, color = neglog10_fdr)) +
    scale_size(range = c(0.8, 3), breaks = pretty_breaks(n = 4)) +
    scale_color_gradient(
      low = "grey30",
      high = dot_color,
      breaks = pretty_breaks(n = 4)
    ) +
    labs(
      title = title,
      x = "Gene ratio",
      y = NULL,
      color = expression(-log[10]("adj. P")),
      size = "\nCount"
    ) +
    theme_pub() +
    theme(
      panel.grid.major = element_line(linewidth = 0.15, color = "grey90"),
      panel.grid.minor = element_blank(),
      axis.text.x = element_text(size = 5),
      axis.text.y = element_text(size = 5),
      axis.title = element_text(size = 5),
      legend.title = element_text(size = 4),
      legend.text = element_text(size = 4),
      legend.key.height = unit(0.35, "cm"),
      legend.key.width = unit(0.2, "cm"),
      legend.spacing.y = unit(0.1, "cm")
    ) +
    guides(
      color = guide_colorbar(
        order = 1,
        barheight = unit(1.5, "cm"),
        barwidth = unit(0.25, "cm")
      ),
      size = guide_legend(
        order = 2,
        keyheight = unit(0.35, "cm"),
        keywidth = unit(0.35, "cm")
      )
    )
}

for (comparison in comparison_levels) {
  timepoint <- str_extract(comparison, "^C\\d+")

  go_df <- run_multi_det_go(comparison, top_n = 8)

  p_go <- plot_go_dot_from_df(
    plot_df = go_df,
    title = paste0("GO: ", timepoint, " Multi-DET Genes"),
    dot_color = comparison_colors[[comparison]]
  )

  save_panel(
    p_go,
    paste0("Fig2C_", timepoint, "_MultiDET_GO.png"),
    width_mm = 62,
    height_mm = 55
  )

  readr::write_csv(
    go_df,
    file.path(figure_dir, paste0("Fig2C_", timepoint, "_MultiDET_GO_source_data.csv"))
  )
}

# ==============================================================================
# Figure 2D: Emergence categories of DETs
# ==============================================================================

emergence_plot_df <- det_emergence %>%
  mutate(
    contrast_pretty = factor(contrast_pretty, levels = comparison_levels),
    baseline_status = factor(
      baseline_status,
      levels = c(
        "Emerged: Remodeling",
        "Emerged: Activation",
        "Expressed at Baseline"
      )
    )
  ) %>%
  count(contrast_pretty, baseline_status) %>%
  group_by(contrast_pretty) %>%
  mutate(frac = n / sum(n)) %>%
  ungroup()

p_emergence <- plot_stacked_percent(
  plot_df = emergence_plot_df,
  x_var = contrast_pretty,
  fill_var = baseline_status,
  y_lab = "Percentage of DETs",
  title = "Emergence of DETs"
) +
  scale_fill_discrete(labels = function(x) str_wrap(x, width = 18))

save_panel(
  p_emergence,
  "Fig2D_DET_Emergence.png",
  width_mm = 52,
  height_mm = 65
)

readr::write_csv(
  emergence_plot_df,
  file.path(figure_dir, "Fig2D_DET_emergence_plot_source_data.csv")
)

# ==============================================================================
# Figure 2E: Structural remodeling among emerged-remodeling DETs
# ==============================================================================

remodel_plot_df <- det_structural %>%
  filter(final_class %in% remodel_class_levels) %>%
  mutate(
    contrast_pretty = factor(contrast_pretty, levels = comparison_levels),
    final_class = factor(final_class, levels = remodel_class_levels)
  ) %>%
  count(contrast_pretty, final_class, name = "n_isoforms") %>%
  complete(
    contrast_pretty = comparison_levels,
    final_class = remodel_class_levels,
    fill = list(n_isoforms = 0)
  ) %>%
  group_by(contrast_pretty) %>%
  mutate(value = 100 * n_isoforms / sum(n_isoforms)) %>%
  ungroup()

p_remodeling <- ggplot(
  remodel_plot_df,
  aes(x = contrast_pretty, y = value, fill = final_class)
) +
  geom_col(width = 0.9, color = "black", linewidth = 0.25) +
  geom_text(
    aes(label = pct_lab_value(value)),
    position = position_stack(vjust = 0.5),
    size = 1.6
  ) +
  scale_y_continuous(
    expand = c(0, 0),
    labels = function(x) paste0(x, "%"),
    position = "right"
  ) +
  coord_cartesian(ylim = c(0, 100)) +
  scale_fill_discrete(
    palette = "Set2",
    labels = function(x) str_wrap(x, width = 18)
  ) +
  labs(
    x = NULL,
    y = NULL,
    title = "Remodeling of DETs",
    fill = NULL
  ) +
  theme_pub() +
  theme(
    legend.position = "bottom",
    legend.box = "horizontal",
    legend.key.size = unit(2, "mm"),
    legend.text = element_text(size = 5),
    legend.spacing.y = unit(1, "mm"),
    legend.spacing.x = unit(1, "mm"),
    legend.box.margin = margin(t = -2, r = -4, b = 0, l = 0, unit = "mm")
  ) +
  guides(fill = guide_legend(nrow = 2, byrow = FALSE))

save_panel(
  p_remodeling,
  "Fig2E_UTR_CDS_ORF_Remodeling.png",
  width_mm = 50,
  height_mm = 68
)

readr::write_csv(
  remodel_plot_df,
  file.path(figure_dir, "Fig2E_UTR_CDS_ORF_remodeling_plot_source_data.csv")
)

message("Figure 2 plotting complete. Outputs saved to: ", figure_dir)
