#!/usr/bin/env Rscript

################################################################################
# Figure 3: Isoform-level analysis reveals differential transcript expression
#  independent of gene-level changes after peripheral nerve injury.
#
# Panels generated by this script:
#   A & D: Short-read vs. long-read gene-level concordance for C3/C7 vs. C0
#   B & E: Differential gene expression volcano plots for C3/C7 vs. C0
#   C & F: Differential transcript expression volcano plots for C3/C7 vs. C0
#
# Panels G - L are generated using:
#     Plotting_isoform_expression.R
#     Plotting_isoform_proportion.R
#     Plotting_isoform_trackplot.R
#
# Inputs:
#   - *_isoform_results.csv
#       from Isoform_Analysis/DTE_Analysis_DESeq2.R
#   - *_inferred_gene_results.csv
#       from Isoform_Analysis/DGE_Analysis_LR_DESeq2.R
#   - *_results.csv
#       from Short_Read/DGE_Analysis_DESeq2.R
#
# Notes:
#   DGE/DTE overlap, Venn diagrams and GO enrichment of DET-only genes are
#   generated in Supplementary_Figure_3.R.
#
################################################################################

suppressPackageStartupMessages({
  library(EnhancedVolcano)
  library(tidyverse)
  library(grid)
})

# ==============================================================================
# User-defined directories
# ==============================================================================

short_read_dir <- "/path/to/short_read_results"                 # <-- MODIFY HERE
results_dir    <- "/path/to/isoform_analysis_results"           # <-- MODIFY HERE
figure_dir     <- "/path/to/Figure_3_output"                    # <-- MODIFY HERE

dir.create(figure_dir, recursive = TRUE, showWarnings = FALSE)

# ==============================================================================
# User-adjustable parameters
# ==============================================================================

padj_cutoff <- 0.05                                             # <-- MODIFY HERE IF NEEDED
lfc_cutoff  <- 1                                                # <-- MODIFY HERE IF NEEDED

# ==============================================================================
# Comparison-specific settings
# ==============================================================================

comparison_config <- list(
  C3 = list(
    short_read_file = "C3_Injured_vs_C0_results.csv",           # <-- MODIFY HERE IF NEEDED
    lr_gene_file    = "C3_vs_C0_inferred_gene_results.csv",     # <-- MODIFY HERE IF NEEDED
    lr_isoform_file = "C3_vs_C0_isoform_results.csv",           # <-- MODIFY HERE IF NEEDED
    contrast_label  = "C3 Injured vs. C0 Control",
    color           = "#E69F00",
    dge_labels      = c("Cdkn2c", "Pdlim7", "Cyth2"),          # <-- MODIFY HERE IF NEEDED
    dte_labels      = c(                                        # <-- MODIFY HERE IF NEEDED
      "Cdkn2c-201", "Cdkn2c-202",
      "Pdlim7-202", "Pdlim7-203", "Pdlim7-204", "Pdlim7-209",
      "Cyth2-202", "Cyth2-204"
    )
  ),

  C7 = list(
    short_read_file = "C7_Injured_vs_C0_results.csv",           # <-- MODIFY HERE IF NEEDED
    lr_gene_file    = "C7_vs_C0_inferred_gene_results.csv",     # <-- MODIFY HERE IF NEEDED
    lr_isoform_file = "C7_vs_C0_isoform_results.csv",           # <-- MODIFY HERE IF NEEDED
    contrast_label  = "C7 Injured vs. C0 Control",
    color           = "#66BD63",
    dge_labels      = c("Itgb5", "Sema4c", "Schip1"),          # <-- MODIFY HERE IF NEEDED
    dte_labels      = c(                                        # <-- MODIFY HERE IF NEEDED
      "Itgb5-202", "Itgb5-201", "Itgb5-207",
      "Schip1-203", "Schip1-205",
      "Sema4c-202", "Sema4c-208"
    )
  )
)

# ==============================================================================
# Input checks
# ==============================================================================

required_files <- c(
  unlist(purrr::map(comparison_config, ~ c(
    file.path(short_read_dir, .x$short_read_file),
    file.path(results_dir, .x$lr_gene_file),
    file.path(results_dir, .x$lr_isoform_file)
  )))
)

missing_files <- required_files[!file.exists(required_files)]

if (length(missing_files) > 0) {
  stop(
    "Missing required file(s):\n",
    paste(missing_files, collapse = "\n"),
    call. = FALSE
  )
}

# ==============================================================================
# Helper functions
# ==============================================================================

theme_volcano <- function(base_size = 7) {
  theme_minimal(base_size = base_size) +
    theme(
      axis.text = element_text(size = 7, color = "black"),
      axis.title = element_text(size = 7, face = "bold"),
      plot.title = element_text(size = 8, face = "bold", hjust = 0.5),
      plot.subtitle = element_text(size = 7, hjust = 0.5),
      plot.caption = element_text(size = 5, color = "gray30"),
      panel.grid = element_blank(),
      axis.line = element_line(color = "black", linewidth = 0.3),
      axis.ticks = element_line(color = "black", linewidth = 0.3),
      axis.ticks.length = unit(0.15, "cm"),
      legend.position = "none"
    )
}

save_panel <- function(plot, filename, width_mm, height_mm) {
  ggsave(
    filename = file.path(figure_dir, filename),
    plot = plot,
    width = width_mm,
    height = height_mm,
    units = "mm",
    dpi = 600,
    bg = "white"
  )
}

plot_concordance <- function(sr_res, lr_gene_res, contrast_label, point_color) {
  lr_gene <- lr_gene_res %>%
    filter(!is.na(gene_symbol), !is.na(log2FoldChange), !is.na(padj)) %>%
    group_by(gene_symbol) %>%
    summarise(lr_gene_log2FC = log2FoldChange[which.min(padj)][1], .groups = "drop")

  sr_gene <- sr_res %>%
    transmute(gene_symbol, sr_gene_log2FC = log2FoldChange, sr_padj = padj) %>%
    filter(!is.na(gene_symbol), !is.na(sr_gene_log2FC), !is.na(sr_padj)) %>%
    distinct(gene_symbol, .keep_all = TRUE)

  plot_df <- inner_join(sr_gene, lr_gene, by = "gene_symbol")

  cor_res <- cor.test(
    plot_df$sr_gene_log2FC,
    plot_df$lr_gene_log2FC,
    method = "spearman",
    exact = FALSE
  )

  r_lab <- sprintf("%.3f", unname(cor_res$estimate))
  p_lab <- if (cor_res$p.value == 0) " P < 1e-300" else sprintf(" P = %.3e", cor_res$p.value)

  message(contrast_label, ": ", nrow(plot_df), " genes, Spearman r = ", r_lab, ",", p_lab)

  p <- ggplot(plot_df, aes(x = sr_gene_log2FC, y = lr_gene_log2FC)) +
    geom_point(alpha = 0.25, size = 0.1, color = point_color) +
    geom_abline(slope = 1, intercept = 0, linetype = "dashed", linewidth = 0.2, color = "red") +
    geom_hline(yintercept = 0, linewidth = 0.2, color = "grey60") +
    geom_vline(xintercept = 0, linewidth = 0.2, color = "grey60") +
    annotate(
      "text",
      x = -Inf,
      y = Inf,
      hjust = 0,
      vjust = 1,
      label = paste0(" Spearman r = ", r_lab, "\n", p_lab),
      size = 2,
      color = "black"
    ) +
    scale_x_continuous(limits = range(plot_df$sr_gene_log2FC, na.rm = TRUE)) +
    scale_y_continuous(limits = range(plot_df$lr_gene_log2FC, na.rm = TRUE)) +
    labs(
      title = "Concordance Plot",
      subtitle = bquote(italic(.(contrast_label))),
      x = expression("srRNA-seq Gene Log"[2] * "FC"),
      y = expression("lrRNA-seq Gene Log"[2] * "FC")
    ) +
    theme_classic(base_size = 7) +
    theme(
      panel.grid = element_blank(),
      axis.ticks = element_line(color = "black", linewidth = 0.3),
      axis.ticks.length = unit(0.12, "cm"),
      axis.text.x = element_text(size = 5),
      axis.text.y = element_text(size = 5),
      axis.title.x = element_text(size = 6, margin = margin(t = 2)),
      axis.title.y = element_text(size = 6, margin = margin(r = 2)),
      plot.title = element_text(size = 7, face = "bold", hjust = 0.5, margin = margin(b = 4)),
      plot.subtitle = element_text(size = 6, hjust = 0.5)
    )

  list(plot = p, data = plot_df)
}

make_volcano <- function(res, label_col, selected_labels, title, subtitle,
                         highlight_color, point_size, max_overlaps) {
  plot_df <- res %>%
    mutate(
      padj = replace_na(padj, 1),
      label = if_else(
        .data[[label_col]] %in% selected_labels,
        .data[[label_col]],
        NA_character_
      )
    )

  EnhancedVolcano(
    plot_df,
    lab = plot_df$label,
    selectLab = selected_labels,
    x = "log2FoldChange",
    y = "padj",
    ylim = c(0, 80),
    pCutoff = padj_cutoff,
    FCcutoff = lfc_cutoff,
    col = c("gray50", "gray50", "gray50", highlight_color),
    boxedLabels = TRUE,
    max.overlaps = max_overlaps,
    labCol = "black",
    labSize = 1.7,
    drawConnectors = TRUE,
    colConnectors = "black",
    widthConnectors = 0.2,
    pointSize = point_size,
    cutoffLineWidth = 0.2,
    xlab = NULL,
    ylab = NULL,
    title = NULL,
    subtitle = NULL,
    caption = NULL,
    gridlines.major = FALSE,
    gridlines.minor = FALSE,
    legendPosition = "none"
  ) +
    theme_volcano() +
    labs(
      x = bquote(~Log[2]~italic(FC)),
      y = bquote(~-Log[10]~italic(adj.~P)),
      title = title,
      subtitle = bquote(italic(.(subtitle)))
    )
}

# ==============================================================================
# Run each comparison
# ==============================================================================

for (comparison in names(comparison_config)) {
  cfg <- comparison_config[[comparison]]
  message("---- ", cfg$contrast_label, " ----")

  sr_res <- read_csv(file.path(short_read_dir, cfg$short_read_file), show_col_types = FALSE)
  gene_res <- read_csv(file.path(results_dir, cfg$lr_gene_file), show_col_types = FALSE)
  transcript_res <- read_csv(file.path(results_dir, cfg$lr_isoform_file), show_col_types = FALSE)

  # ----------------------------------------------------------------------------
  # Figure 3A/D: Short-read vs. long-read gene-level concordance
  # ----------------------------------------------------------------------------

  concordance <- plot_concordance(sr_res, gene_res, cfg$contrast_label, cfg$color)

  save_panel(
    concordance$plot,
    paste0("Fig3_", comparison, "_Concordance.png"),
    width_mm = 53,
    height_mm = 59
  )

  write_csv(
    concordance$data,
    file.path(figure_dir, paste0("Fig3_", comparison, "_Concordance_source_data.csv"))
  )

  # ----------------------------------------------------------------------------
  # Figure 3B/E and 3C/F: DGE and DTE volcano plots
  # ----------------------------------------------------------------------------

  p_dge <- make_volcano(
    res = gene_res,
    label_col = "gene_symbol",
    selected_labels = cfg$dge_labels,
    title = "Differential Gene Expression",
    subtitle = cfg$contrast_label,
    highlight_color = cfg$color,
    point_size = 0.7,
    max_overlaps = Inf
  )

  save_panel(p_dge, paste0("Fig3_", comparison, "_DGE.png"), width_mm = 75, height_mm = 68)

  p_dte <- make_volcano(
    res = transcript_res,
    label_col = "transcript_symbol",
    selected_labels = cfg$dte_labels,
    title = "Differential Transcript Expression",
    subtitle = cfg$contrast_label,
    highlight_color = cfg$color,
    point_size = 0.7,
    max_overlaps = Inf
  )

  save_panel(p_dte, paste0("Fig3_", comparison, "_DTE.png"), width_mm = 75, height_mm = 68)
}

message("Figure 3 complete. Outputs saved to: ", figure_dir)
