#!/usr/bin/env Rscript

# =============================================================================
# Figure 5: Characterization of novel isoforms and validation of Lama4-novel-6 
#  after peripheral nerve 
#
# Panels generated by this script:
#   A: Novel isoform length distribution
#   B: Novel isoform exon count distribution
#   C: Novel isoform subcategory pie chart
#   D: Injury-induced/repressed novel isoform counts
#   G: Lama4 FeaturePlot across time points
#   H: Lama4-novel qPCR validation
#
# Panels generated by shared scripts:
#   E: Plotting_isoform_expression.R using Lama4 as input
#   F: Plotting_isoform_trackplot.R using Lama4 isoforms as input
#
# =============================================================================

suppressPackageStartupMessages({
  library(tidyverse)
  library(Seurat)
  library(patchwork)
  library(RColorBrewer)
  library(rstatix)
  library(grid)
})

# =============================================================================
# User-defined files/directories
# =============================================================================

sqanti_class_dir <- "/path/to/Filtered_SQANTI3_Results"          # <-- MODIFY HERE
isoform_results_dir <- "/path/to/isoform_analysis_results"       # <-- MODIFY HERE
single_cell_results_dir <- "/path/to/single_cell_results"        # <-- MODIFY HERE
figure_dir <- "/path/to/Figure_5_output"                         # <-- MODIFY HERE

qPCR_path <- "/path/to/Lama4_qPCR.csv"                           # <-- MODIFY HERE

seurat_object_path <- file.path(
  single_cell_results_dir,
  "integrated_annotated_seurat_object.rds"
)                                                                 # <-- MODIFY HERE IF NEEDED

dir.create(figure_dir, recursive = TRUE, showWarnings = FALSE)

# =============================================================================
# Input files
# =============================================================================

classification_files <- c(                                      # <-- MODIFY HERE IF NEEDED
  "C0_Sciatic_1_filtered_RulesFilter_result_classification_with_rescue_flag_with_transcriptID.txt",
  "C0_Sciatic_2_filtered_RulesFilter_result_classification_with_rescue_flag_with_transcriptID.txt",
  "C0_Sciatic_3_filtered_RulesFilter_result_classification_with_rescue_flag_with_transcriptID.txt",
  "C3_Injured_Sciatic_1_filtered_RulesFilter_result_classification_with_rescue_flag_with_transcriptID.txt",
  "C3_Injured_Sciatic_2_filtered_RulesFilter_result_classification_with_rescue_flag_with_transcriptID.txt",
  "C3_Injured_Sciatic_3_filtered_RulesFilter_result_classification_with_rescue_flag_with_transcriptID.txt",
  "C7_Injured_Sciatic_1_filtered_RulesFilter_result_classification_with_rescue_flag_with_transcriptID.txt",
  "C7_Injured_Sciatic_2_filtered_RulesFilter_result_classification_with_rescue_flag_with_transcriptID.txt",
  "C7_Injured_Sciatic_3_filtered_RulesFilter_result_classification_with_rescue_flag_with_transcriptID.txt"
)

classification_paths <- file.path(sqanti_class_dir, classification_files)

counts_filtered_path <- file.path(
  isoform_results_dir,
  "Counts_filtered.tsv"
)                                                                 # <-- MODIFY HERE IF NEEDED

c3_dte_path <- file.path(
  isoform_results_dir,
  "C3_vs_C0_isoform_results.csv"
)                                                                 # <-- MODIFY HERE IF NEEDED

c7_dte_path <- file.path(
  isoform_results_dir,
  "C7_vs_C0_isoform_results.csv"
)                                                                 # <-- MODIFY HERE IF NEEDED

required_files <- c(
  classification_paths,
  counts_filtered_path,
  c3_dte_path,
  c7_dte_path
)

missing_files <- required_files[!file.exists(required_files)]

if (length(missing_files) > 0) {
  stop(
    "Missing required file(s):\n",
    paste(missing_files, collapse = "\n"),
    call. = FALSE
  )
}

# =============================================================================
# User-adjustable parameters
# =============================================================================

padj_cutoff <- 0.05                                             # <-- MODIFY HERE IF NEEDED
lfc_cutoff <- 1                                                 # <-- MODIFY HERE IF NEEDED

timepoint_order <- c("C0", "C3", "C7")                         # <-- MODIFY HERE IF NEEDED
lama4_feature <- "Lama4"                                       

condition_colors <- c(
  "C0 Control" = "#0072B2",
  "C3 Injured" = "#E69F00",
  "C7 Injured" = "#66BD63"
)

comparison_colors <- c(
  "C3 vs. C0" = "#E69F00",
  "C7 vs. C0" = "#66BD63"
)

# =============================================================================
# Helper functions
# =============================================================================

get_sample_name <- function(path) {
  basename(path) %>%
    str_replace(
      "_filtered_RulesFilter_result_classification_with_rescue_flag_with_transcriptID.txt",
      ""
    )
}

theme_pub <- function(base_size = 7) {
  theme_minimal(base_size = base_size) +
    theme(
      axis.line = element_line(color = "black", linewidth = 0.3),
      axis.ticks = element_line(color = "black", linewidth = 0.3),
      axis.ticks.length = unit(0.15, "cm"),
      panel.grid = element_blank(),
      axis.text.x = element_text(size = 5, color = "black"),
      axis.text.y = element_text(size = 5, color = "black"),
      axis.title = element_text(size = 6),
      plot.title = element_text(
        size = 7,
        face = "bold",
        hjust = 0.5,
        margin = margin(b = 4)
      ),
      plot.margin = margin(t = 6, r = 6, b = 4, l = 4, unit = "mm")
    )
}

save_panel <- function(plot, filename, width_mm, height_mm, device = "png") {
  ggsave(
    filename = file.path(figure_dir, filename),
    plot = plot,
    width = width_mm,
    height = height_mm,
    units = "mm",
    dpi = 600,
    bg = "white",
    device = device
  )
}

# =============================================================================
# Panels A-D: Novel isoform characterization
# =============================================================================

novel_data <- purrr::map_dfr(classification_paths, function(path) {
  readr::read_tsv(path, show_col_types = FALSE) %>%
    filter(
      filter_rescued_result == "Isoform",
      structural_category %in% c("novel_in_catalog", "novel_not_in_catalog"),
      str_starts(associated_gene, "ENSMUSG")
    ) %>%
    mutate(Sample = get_sample_name(path))
})

counts_filtered <- readr::read_tsv(counts_filtered_path, show_col_types = FALSE)

expr_filtered_ids <- counts_filtered$transcript_symbol

novel_filtered <- novel_data %>%
  filter(transcript_id %in% expr_filtered_ids)

readr::write_tsv(
  novel_filtered %>%
    arrange(desc(structural_category), associated_gene),
  file.path(figure_dir, "Filtered_NovelIsoforms_counts10_in2samples.tsv")
)

length_col <- intersect(
  c("length", "length_nt", "Transcript_length"),
  colnames(novel_filtered)
)[1]

exon_col <- intersect(
  c("exons", "exon_count", "n_exons"),
  colnames(novel_filtered)
)[1]

if (is.na(length_col)) {
  stop("Could not identify transcript length column.")
}

if (is.na(exon_col)) {
  stop("Could not identify exon count column.")
}

# -----------------------------------------------------------------------------
# Figure 5A: Novel isoform length distribution
# -----------------------------------------------------------------------------

p_length <- ggplot(novel_filtered, aes(x = .data[[length_col]])) +
  geom_histogram(
    bins = 30,
    fill = "#009E73",
    color = "black",
    linewidth = 0.2
  ) +
  labs(
    x = "Transcript Length (nt)",
    y = "Number of Novel Isoforms",
    title = "Length Distribution of\nNovel Isoforms from Known Genes"
  ) +
  theme_pub()

save_panel(
  p_length,
  "Fig5A_NovelIsoform_LengthDistribution.png",
  width_mm = 60,
  height_mm = 60
)

# -----------------------------------------------------------------------------
# Figure 5B: Novel isoform exon count distribution
# -----------------------------------------------------------------------------

p_exons <- ggplot(novel_filtered, aes(x = .data[[exon_col]])) +
  geom_histogram(
    bins = 30,
    fill = "#009E73",
    color = "black",
    linewidth = 0.2
  ) +
  labs(
    x = "Number of Exons",
    y = "Number of Novel Isoforms",
    title = "Exon Count Distribution of\nNovel Isoforms from Known Genes"
  ) +
  theme_pub()

save_panel(
  p_exons,
  "Fig5B_NovelIsoform_ExonCountDistribution.png",
  width_mm = 60,
  height_mm = 60
)

# Save summary statistics
novel_summary_stats <- tibble(
  metric = c(
    "min_length",
    "median_length",
    "max_length",
    "min_exons",
    "median_exons",
    "max_exons"
  ),
  value = c(
    min(novel_filtered[[length_col]], na.rm = TRUE),
    median(novel_filtered[[length_col]], na.rm = TRUE),
    max(novel_filtered[[length_col]], na.rm = TRUE),
    min(novel_filtered[[exon_col]], na.rm = TRUE),
    median(novel_filtered[[exon_col]], na.rm = TRUE),
    max(novel_filtered[[exon_col]], na.rm = TRUE)
  )
)

readr::write_csv(
  novel_summary_stats,
  file.path(figure_dir, "Fig5AB_NovelIsoform_summary_statistics.csv")
)

# -----------------------------------------------------------------------------
# Figure 5C: Novel isoform subcategory pie chart
# -----------------------------------------------------------------------------

subcategory_summary <- novel_filtered %>%
  count(subcategory) %>%
  mutate(
    subcategory_label = case_when(
      subcategory == "combination_of_known_junctions" ~ "Combination of\nKnown Junctions",
      subcategory == "combination_of_known_splicesites" ~ "Combination of\nKnown Splicesites",
      subcategory == "at_least_one_novel_splicesite" ~ "At Least One\nNovel Splicesite",
      subcategory == "intron_retention" ~ "Intron\nRetention",
      TRUE ~ subcategory
    ),
    Percent = 100 * n / sum(n),
    label = paste0(subcategory_label, "\n", sprintf("%.1f%%", Percent))
  ) %>%
  arrange(desc(Percent))

pie_colors <- c(
  "Combination of\nKnown Junctions" = "#4575B4",
  "Combination of\nKnown Splicesites" = "#ABD9E9",
  "At Least One\nNovel Splicesite" = "#F46D43",
  "Intron\nRetention" = "#FEE08B"
)

p_pie <- ggplot(
  subcategory_summary,
  aes(x = "", y = Percent, fill = subcategory_label)
) +
  geom_col(width = 1, color = "black", linewidth = 0.25) +
  coord_polar(theta = "y") +
  geom_text(
    aes(label = label, x = 1.05),
    position = position_stack(vjust = 0.5),
    size = 2.2,
    color = "black",
    lineheight = 0.95,
    fontface = "bold"
  ) +
  scale_fill_manual(values = pie_colors) +
  labs(
    title = "Subcategory of Novel Isoforms",
    fill = "Novel Isoform Subcategory"
  ) +
  theme_void(base_size = 7) +
  theme(
    plot.title = element_text(
      size = 8,
      face = "bold",
      hjust = 0.5,
      margin = margin(b = -5)
    ),
    legend.position = "none",
    plot.margin = margin(t = 4, r = 4, b = 4, l = 4, unit = "mm")
  )

ggsave(
  file.path(figure_dir, "Fig5C_NovelIsoform_SubcategoryPieChart.pdf"),
  p_pie,
  width = 70,
  height = 90,
  units = "mm",
  dpi = 600,
  useDingbats = FALSE
)

readr::write_csv(
  subcategory_summary,
  file.path(figure_dir, "Fig5C_NovelIsoform_Subcategory_source_data.csv")
)

# -----------------------------------------------------------------------------
# Figure 5D: Injury-induced/repressed novel isoform counts
# -----------------------------------------------------------------------------

c3_res <- readr::read_csv(c3_dte_path, show_col_types = FALSE) %>%
  mutate(contrast = "C3 vs. C0")

c7_res <- readr::read_csv(c7_dte_path, show_col_types = FALSE) %>%
  mutate(contrast = "C7 vs. C0")

lr_novel <- bind_rows(c3_res, c7_res) %>%
  filter(!is.na(padj), padj <= padj_cutoff, abs(log2FoldChange) >= lfc_cutoff) %>%
  filter(transcript_id %in% novel_filtered$transcript_id) %>%
  mutate(
    regulation = case_when(
      log2FoldChange > lfc_cutoff ~ "Induced",
      log2FoldChange < -lfc_cutoff ~ "Repressed",
      TRUE ~ NA_character_
    )
  ) %>%
  filter(!is.na(regulation))

plot_df <- lr_novel %>%
  count(contrast, regulation) %>%
  mutate(
    contrast = factor(contrast, levels = c("C3 vs. C0", "C7 vs. C0")),
    regulation = factor(regulation, levels = c("Repressed", "Induced")),
    n_isoforms = if_else(regulation == "Repressed", -n, n)
  )

max_val <- max(abs(plot_df$n_isoforms), na.rm = TRUE)
min_val <- min(plot_df$n_isoforms, na.rm = TRUE)

p_novel_count <- ggplot(
  plot_df,
  aes(x = contrast, y = n_isoforms, fill = contrast)
) +
  geom_col(color = "black", linewidth = 0.2) +
  geom_text(
    aes(label = abs(n_isoforms)),
    position = position_stack(vjust = 0.5),
    hjust = 0.5,
    size = 2,
    color = "black"
  ) +
  geom_hline(yintercept = 0, linewidth = 0.2, linetype = "dashed") +
  scale_y_continuous(
    limits = c(min_val, max_val),
    breaks = c(min_val * 0.6, 0, max_val * 0.6),
    labels = c("Repressed", "", "Induced")
  ) +
  scale_fill_manual(values = comparison_colors) +
  labs(
    x = NULL,
    y = NULL,
    title = "Novel Isoform Regulation"
  ) +
  theme_pub() +
  theme(
    axis.text.x = element_text(size = 6),
    axis.text.y = element_text(size = 6, angle = 90, hjust = 0.5),
    legend.position = "none",
    plot.margin = margin(t = 8, r = 2, b = 4, l = 4, unit = "mm")
  )

save_panel(
  p_novel_count,
  "Fig5D_NovelIsoform_Counts.png",
  width_mm = 40,
  height_mm = 55
)

readr::write_csv(
  lr_novel,
  file.path(figure_dir, "Fig5D_NovelIsoform_Regulation_source_data.csv")
)

# =============================================================================
# Panels E-F are generated by shared scripts
# =============================================================================
#
# Figure 5E:
#   Use Plotting_isoform_expression.R with:
#     gene_of_interest <- "Lama4"
#
# Figure 5F:
#   Use Plotting_isoform_trackplot.R with Lama4 known and novel isoforms.
#
# =============================================================================

# =============================================================================
# Figure 5G: Lama4 FeaturePlot across time points
# =============================================================================

if (file.exists(seurat_object_path)) {
  obj <- readRDS(seurat_object_path)

  if (lama4_feature %in% rownames(obj)) {
    plot_list <- lapply(timepoint_order, function(tp) {
      obj_sub <- subset(obj, subset = timepoint == tp)

      FeaturePlot(
        obj_sub,
        features = lama4_feature,
        reduction = "umap.harmony",
        order = FALSE,
        pt.size = 0.01,
        raster = FALSE
      ) +
        scale_color_gradientn(
          colors = rev(RColorBrewer::brewer.pal(11, "Spectral"))
        ) +
        theme(
          legend.position = "right",
          plot.title = element_text(size = 10, face = "bold"),
          axis.title = element_text(size = 8),
          axis.text = element_text(size = 6),
          legend.title = element_text(size = 8),
          legend.text = element_text(size = 6)
        ) +
        ggtitle(paste(lama4_feature, "-", tp))
    })

    p_lama4_feature <- patchwork::wrap_plots(plot_list, ncol = length(timepoint_order))

    save_panel(
      p_lama4_feature,
      "Fig5G_FeaturePlot_Lama4.png",
      width_mm = 170,
      height_mm = 60
    )
  } else {
    warning("Lama4 feature not found in Seurat object: ", lama4_feature)
  }
} else {
  warning("Seurat object not found; skipping Figure 5G: ", seurat_object_path)
}

# =============================================================================
# Figure 5H: Lama4 qPCR validation
# =============================================================================

if (file.exists(qPCR_path)) {
  qPCR_data <- readr::read_csv(qPCR_path, show_col_types = FALSE) %>%
    mutate(
      delta_delta_Ct = delta_Ct_Novel - delta_Ct_Total,
      Ratio = 2^(-delta_delta_Ct)
    )

  qPCR_summary <- qPCR_data %>%
    group_by(Sample) %>%
    summarise(
      Mean = mean(Ratio, na.rm = TRUE),
      SEM = sd(Ratio, na.rm = TRUE) / sqrt(n()),
      .groups = "drop"
    )

  qPCR_data2 <- qPCR_data %>%
    left_join(qPCR_summary, by = "Sample") %>%
    mutate(
      Sample = factor(
        Sample,
        levels = c("C0 Control", "C3 Injured", "C7 Injured")
      )
    )

  p_iso <- ggplot(qPCR_data2, aes(x = Sample, y = Ratio, fill = Sample)) +
    stat_summary(
      fun = mean,
      geom = "bar",
      width = 0.7,
      color = "black",
      linewidth = 0.2
    ) +
    stat_summary(
      fun.data = mean_se,
      geom = "errorbar",
      width = 0.3,
      linewidth = 0.2
    ) +
    labs(
      x = NULL,
      y = "qPCR Novel/Total Lama4\n(Mean ± SEM)",
      title = "Relative Abundance of Lama4-novel-6"
    ) +
    scale_fill_manual(values = condition_colors) +
    theme_pub() +
    theme(
      axis.title.y = element_text(size = 6, margin = margin(r = 3)),
      legend.position = "none",
      plot.margin = margin(t = 8, r = 8, b = 4, l = 4, unit = "mm")
    )

  ymax <- max(qPCR_data2$Ratio, na.rm = TRUE)
  y1 <- ymax * 0.90
  y2 <- ymax * 0.95
  tick <- ymax * 0.03

  p_iso <- p_iso +
    annotate("segment", x = 1, xend = 2, y = y1, yend = y1, linewidth = 0.3) +
    annotate("segment", x = 1, xend = 1, y = y1, yend = y1 - tick, linewidth = 0.3) +
    annotate("segment", x = 2, xend = 2, y = y1, yend = y1 - tick, linewidth = 0.3) +
    annotate("text", x = 1.5, y = y1, label = "*", vjust = 0.5, size = 3) +
    annotate("segment", x = 1, xend = 3, y = y2, yend = y2, linewidth = 0.3) +
    annotate("segment", x = 1, xend = 1, y = y2, yend = y2 - tick, linewidth = 0.3) +
    annotate("segment", x = 3, xend = 3, y = y2, yend = y2 - tick, linewidth = 0.3) +
    annotate("text", x = 2, y = y2, label = "*", vjust = 0.5, size = 3)

  ggsave(
    file.path(figure_dir, "Fig5H_Lama4_qPCR.pdf"),
    p_iso,
    width = 55,
    height = 48,
    units = "mm",
    dpi = 600,
    useDingbats = FALSE
  )

  readr::write_csv(
    qPCR_data2,
    file.path(figure_dir, "Fig5H_Lama4_qPCR_source_data.csv")
  )

  qpcr_tests <- bind_rows(
    broom::tidy(t.test(
      delta_delta_Ct ~ Sample,
      data = subset(qPCR_data2, Sample %in% c("C0 Control", "C3 Injured"))
    )) %>%
      mutate(comparison = "C0 Control vs C3 Injured"),
    broom::tidy(t.test(
      delta_delta_Ct ~ Sample,
      data = subset(qPCR_data2, Sample %in% c("C0 Control", "C7 Injured"))
    )) %>%
      mutate(comparison = "C0 Control vs C7 Injured")
  )

  readr::write_csv(
    qpcr_tests,
    file.path(figure_dir, "Fig5H_Lama4_qPCR_t_tests.csv")
  )
} else {
  warning("qPCR file not found; skipping Figure 5H: ", qPCR_path)
}

message("Figure 5 plotting complete. Outputs saved to: ", figure_dir)
