#!/usr/bin/env Rscript

# =============================================================================
# Figure 6: Differential transcript usage and Postn isoform validation
# =============================================================================
#
# Panels generated by this script:
#   A: C3 vs C0 DTU volcano plot
#   B: C7 vs C0 DTU volcano plot
#   C: DGE/DTE/DTU Venn diagram
#   F: Postn qPCR validation
#
# Panels generated by shared scripts:
#   D: Plotting_isoform_proportion.R using Postn as input
#   E: Plotting_isoform_expression.R using Postn as input
#   G: Plotting_isoform_trackplot.R using Postn isoforms as input
#
# Assumes DTU_Analysis_IsoformSwitchAnalyzeR_DEXSeq.R has already been run.
#
# =============================================================================

suppressPackageStartupMessages({
  library(tidyverse)
  library(EnhancedVolcano)
  library(VennDiagram)
  library(grid)
  library(AnnotationDbi)
  library(org.Mm.eg.db)
  library(RColorBrewer)
})

# =============================================================================
# User-defined files/directories
# =============================================================================

short_read_dir <- "/path/to/short_read_results"                 # <-- MODIFY HERE
isoform_results_dir <- "/path/to/isoform_analysis_results"      # <-- MODIFY HERE
dtu_results_dir <- "/path/to/isoform_switching_results"         # <-- MODIFY HERE
figure_dir <- "/path/to/Figure_6_output"                        # <-- MODIFY HERE

postn_qpcr_path <- "/path/to/Postn_qPCR.csv"                    # <-- MODIFY HERE

dir.create(figure_dir, recursive = TRUE, showWarnings = FALSE)

# =============================================================================
# Input files
# =============================================================================

dtu_results_path <- file.path(
  dtu_results_dir,
  "All_Isoform_Switching_Events_Annotated.csv"
)                                                                 # <-- MODIFY HERE IF NEEDED

required_files <- c(dtu_results_path)

missing_files <- required_files[!file.exists(required_files)]

if (length(missing_files) > 0) {
  stop(
    "Missing required file(s):\n",
    paste(missing_files, collapse = "\n"),
    call. = FALSE
  )
}

# =============================================================================
# Parameters
# =============================================================================

padj_cutoff <- 0.05                                             # <-- MODIFY HERE IF NEEDED
lfc_cutoff <- 1                                                 # <-- MODIFY HERE IF NEEDED
dIF_cutoff <- 0.1                                               # <-- MODIFY HERE IF NEEDED

comparison_config <- list(
  C3 = list(
    condition_1 = "C0",
    condition_2 = "C3",
    short_read_file = "C3_Injured_vs_C0_results.csv",
    dte_file = "C3_vs_C0_isoform_results.csv",
    title = "C3 Injured vs. C0 Control",
    color = "#E69F00",
    dtu_output = "Fig6A_C3_DTU.png",
    venn_output = "Fig6C_C3_DGE_DTE_DTU_Venn.png",
    label_genes = c("Postn", "Lgals3", "Pmp22", "Ccl6"),
    exclude_transcripts = c("Lgals3-201")
  ),
  C7 = list(
    condition_1 = "C0",
    condition_2 = "C7",
    short_read_file = "C7_Injured_vs_C0_results.csv",
    dte_file = "C7_vs_C0_isoform_results.csv",
    title = "C7 Injured vs. C0 Control",
    color = "#66BD63",
    dtu_output = "Fig6B_C7_DTU.png",
    venn_output = "Fig6C_C7_DGE_DTE_DTU_Venn.png",
    label_genes = c("Pdlim7", "Plxnb2", "Sgk1", "Tap2"),
    exclude_transcripts = c("Sgk1-202", "Lgals3-201", "Pdlim7-202", "Pdlim-209")
  )
)

# =============================================================================
# Helper functions
# =============================================================================

save_panel <- function(plot, filename, width_mm, height_mm) {
  ggsave(
    filename = file.path(figure_dir, filename),
    plot = plot,
    width = width_mm,
    height = height_mm,
    units = "mm",
    dpi = 600,
    bg = "white"
  )
}

theme_volcano <- function(base_size = 7) {
  theme_minimal(base_size = base_size) +
    theme(
      axis.text = element_text(size = 6, color = "black"),
      axis.title = element_text(size = 6, face = "bold"),
      plot.title = element_text(size = 7, face = "bold", hjust = 0.5),
      plot.subtitle = element_text(size = 6, hjust = 0.5),
      plot.caption = element_text(size = 5, color = "gray30"),
      panel.grid = element_blank(),
      axis.line = element_line(color = "black", linewidth = 0.3),
      axis.ticks = element_line(color = "black", linewidth = 0.3),
      axis.ticks.length = unit(0.15, "cm"),
      legend.position = "none"
    )
}

theme_pub <- function(base_size = 7) {
  theme_minimal(base_size = base_size) +
    theme(
      axis.line = element_line(color = "black", linewidth = 0.3),
      axis.ticks = element_line(color = "black", linewidth = 0.3),
      axis.ticks.length = unit(0.15, "cm"),
      panel.grid = element_blank(),
      axis.text.x = element_text(size = 5, color = "black"),
      axis.text.y = element_text(size = 5, color = "black"),
      axis.title.y = element_text(size = 6, margin = margin(r = 3)),
      plot.title = element_text(size = 7, face = "bold", hjust = 0.5, margin = margin(b = 4)),
      plot.margin = margin(t = 8, r = 8, b = 4, l = 4, unit = "mm")
    )
}

make_dtu_volcano <- function(dtu_df, cfg) {
  plot_df <- dtu_df %>%
    filter(
      condition_1 == cfg$condition_1,
      condition_2 == cfg$condition_2
    ) %>%
    mutate(
      significant = abs(dIF) > dIF_cutoff & padj < padj_cutoff,
      label = case_when(
        gene_id %in% cfg$label_genes &
          !transcript_symbol %in% cfg$exclude_transcripts ~ transcript_symbol,
        TRUE ~ NA_character_
      )
    )

  EnhancedVolcano(
    plot_df,
    lab = plot_df$label,
    selectLab = plot_df$label,
    x = "dIF",
    y = "padj",
    pCutoff = padj_cutoff,
    FCcutoff = dIF_cutoff,
    xlim = c(-1.1, 1.1),
    col = c("gray50", "gray50", "gray50", cfg$color),
    boxedLabels = TRUE,
    max.overlaps = 20,
    labCol = "black",
    labSize = 1.5,
    drawConnectors = TRUE,
    colConnectors = "black",
    widthConnectors = 0.2,
    pointSize = 0.8,
    cutoffLineWidth = 0.2,
    xlab = NULL,
    ylab = NULL,
    title = NULL,
    subtitle = NULL,
    caption = NULL,
    gridlines.major = FALSE,
    gridlines.minor = FALSE,
    legendPosition = "none"
  ) +
    labs(
      x = bquote("Δ Isoform Fraction (dIF)"),
      y = bquote(~-Log[10]~italic(adj.~P)),
      title = "Differential Transcript Usage",
      subtitle = bquote(italic(.(cfg$title)))
    ) +
    theme_volcano()
}

fix_dtu_gene_ids <- function(dtu_filter) {
  needs_fix <- !grepl("^ENSMUSG", dtu_filter$associated_gene)

  symbols_to_map <- unique(dtu_filter$gene_id[needs_fix])

  if (length(symbols_to_map) > 0) {
    map_tbl <- AnnotationDbi::select(
      org.Mm.eg.db,
      keys = symbols_to_map,
      keytype = "SYMBOL",
      columns = c("ENSEMBL")
    ) %>%
      distinct(SYMBOL, ENSEMBL) %>%
      group_by(SYMBOL) %>%
      slice_head(n = 1) %>%
      ungroup()
  } else {
    map_tbl <- tibble(SYMBOL = character(), ENSEMBL = character())
  }

  dtu_filter %>%
    rename(gene_ensembl_id_original = associated_gene) %>%
    left_join(map_tbl, by = c("gene_id" = "SYMBOL")) %>%
    mutate(
      associated_gene = if_else(
        grepl("^ENSMUSG", gene_ensembl_id_original),
        gene_ensembl_id_original,
        ENSEMBL
      ),
      associated_gene = if_else(
        is.na(associated_gene) | !grepl("^ENSMUSG", associated_gene),
        paste0("UNMAPPED_", gene_id),
        associated_gene
      )
    ) %>%
    select(-ENSEMBL)
}

make_dge_dte_dtu_venn <- function(cfg, comparison) {
  gene_file <- file.path(short_read_dir, cfg$short_read_file)
  transcript_file <- file.path(isoform_results_dir, cfg$dte_file)

  if (!file.exists(gene_file)) stop("Missing short-read file: ", gene_file)
  if (!file.exists(transcript_file)) stop("Missing DTE file: ", transcript_file)

  gene <- readr::read_csv(gene_file, show_col_types = FALSE) %>%
    filter(!is.na(padj), padj < padj_cutoff, abs(log2FoldChange) > lfc_cutoff) %>%
    mutate(gene_symbol = coalesce(gene_symbol, ensembl_id))

  transcript <- readr::read_csv(transcript_file, show_col_types = FALSE) %>%
    filter(!is.na(padj), padj <= padj_cutoff, abs(log2FoldChange) >= lfc_cutoff)

  dtu_filter <- all_switches_annotated %>%
    filter(condition_1 == "C0", condition_2 == comparison) %>%
    filter(!is.na(padj), padj <= padj_cutoff, abs(dIF) >= dIF_cutoff) %>%
    fix_dtu_gene_ids()

  venn_plot <- venn.diagram(
    x = list(
      DGE = gene$ensembl_id,
      DTE = transcript$associated_gene,
      DTU = dtu_filter$associated_gene
    ),
    filename = NULL,
    fill = c("skyblue", "lightyellow", "lightgreen"),
    alpha = 0.5,
    cex = 1.5,
    cat.cex = 1.5,
    main = paste0(comparison, " Injured vs. C0 Control"),
    main.cex = 2
  )

  png(
    filename = file.path(figure_dir, cfg$venn_output),
    width = 80,
    height = 80,
    units = "mm",
    res = 600,
    bg = "white"
  )

  grid.newpage()
  grid.draw(venn_plot)
  dev.off()

  readr::write_csv(
    gene,
    file.path(figure_dir, paste0("Fig6C_", comparison, "_DGE_genes_source_data.csv"))
  )

  readr::write_csv(
    transcript,
    file.path(figure_dir, paste0("Fig6C_", comparison, "_DTE_genes_source_data.csv"))
  )

  readr::write_csv(
    dtu_filter,
    file.path(figure_dir, paste0("Fig6C_", comparison, "_DTU_genes_source_data.csv"))
  )
}

# =============================================================================
# Load DTU results
# =============================================================================

all_switches_annotated <- readr::read_csv(
  dtu_results_path,
  show_col_types = FALSE
)

# =============================================================================
# Figure 6A: DTU volcano plots
# =============================================================================

for (comparison in names(comparison_config)) {
  cfg <- comparison_config[[comparison]]

  p_dtu <- make_dtu_volcano(
    dtu_df = all_switches_annotated,
    cfg = cfg
  )

  save_panel(
    p_dtu,
    cfg$dtu_output,
    width_mm = 60,
    height_mm = 70
  )
}

# =============================================================================
# Figure 6C: DGE/DTE/DTU Venn diagrams
# =============================================================================

for (comparison in names(comparison_config)) {
  cfg <- comparison_config[[comparison]]
  make_dge_dte_dtu_venn(cfg, comparison)
}

# =============================================================================
# Panels D/E/G generated by shared scripts
# =============================================================================
#
# Figure 6D:
#   Use Plotting_isoform_proportion.R with:
#     gene_of_interest <- "Postn"
#
# Figure 6E:
#   Use Plotting_isoform_expression.R with:
#     gene_of_interest <- "Postn"
#
# Figure 6G:
#   Use Plotting_isoform_trackplot.R with Postn isoforms.
#
# =============================================================================

# =============================================================================
# Figure 6F: Postn qPCR validation
# =============================================================================

if (!file.exists(postn_qpcr_path)) {
  warning("Postn qPCR file not found; skipping Figure 6F: ", postn_qpcr_path)
} else {
  qPCR_data <- readr::read_csv(postn_qpcr_path, show_col_types = FALSE) %>%
    mutate(
      `Postn Transcript` = factor(
        `Postn Transcript`,
        levels = c("Pan-Postn", "Postn-201", "Postn-202", "Postn-203", "Postn-204")
      ),
      Condition = factor(
        Condition,
        levels = c("C0 Control", "C3 Injured", "C7 Injured")
      )
    )

  qPCR_summary <- qPCR_data %>%
    group_by(`Postn Transcript`, Condition) %>%
    summarise(
      Mean = mean(Value, na.rm = TRUE),
      SEM = sd(Value, na.rm = TRUE) / sqrt(sum(!is.na(Value))),
      .groups = "drop"
    )

  safe_t_p <- function(df, groups) {
    df2 <- df %>%
      filter(Condition %in% groups, !is.na(Value), Value > 0) %>%
      droplevels() %>%
      mutate(logValue = log2(Value))

    if (n_distinct(df2$Condition) != 2) return(NA_real_)

    t.test(logValue ~ Condition, data = df2)$p.value
  }

  stat_test <- map_dfr(levels(qPCR_data$`Postn Transcript`), function(tx) {
    subdat <- qPCR_data %>%
      filter(`Postn Transcript` == tx)

    tibble(
      `Postn Transcript` = tx,
      comparison = c("C3 vs C0", "C7 vs C0"),
      p = c(
        safe_t_p(subdat, c("C0 Control", "C3 Injured")),
        safe_t_p(subdat, c("C0 Control", "C7 Injured"))
      )
    )
  }) %>%
    mutate(
      sig = case_when(
        is.na(p) ~ "ns",
        p <= 1e-4 ~ "****",
        p <= 1e-3 ~ "***",
        p <= 1e-2 ~ "**",
        p <= 0.05 ~ "*",
        TRUE ~ "ns"
      )
    )

  condition_fill <- c(
    "C0 Control" = "#0072B2",
    "C3 Injured" = "#E69F00",
    "C7 Injured" = "#66BD63"
  )

  p_iso <- ggplot(
    qPCR_summary,
    aes(x = `Postn Transcript`, y = Mean, fill = Condition)
  ) +
    geom_bar(
      stat = "identity",
      position = position_dodge(width = 0.8),
      width = 0.7,
      color = "black",
      linewidth = 0.2
    ) +
    geom_errorbar(
      aes(ymin = Mean - SEM, ymax = Mean + SEM),
      position = position_dodge(width = 0.8),
      width = 0.3,
      linewidth = 0.2
    ) +
    labs(
      x = NULL,
      y = "Relative Expression (Mean ± SEM)",
      title = "RT-qPCR Expression of Postn Isoforms"
    ) +
    scale_fill_manual(values = condition_fill) +
    theme_pub() +
    theme(
      legend.position = "right",
      legend.background = element_rect(color = "black", fill = "white", linewidth = 0.3),
      legend.key.size = unit(3, "mm"),
      legend.text = element_text(size = 5),
      legend.title = element_blank()
    )

  offset <- 0.8 / 3
  tick <- 0.04 * max(qPCR_summary$Mean + qPCR_summary$SEM, na.rm = TRUE)
  step <- 0.08 * max(qPCR_summary$Mean + qPCR_summary$SEM, na.rm = TRUE)

  x_df <- qPCR_summary %>%
    distinct(`Postn Transcript`) %>%
    arrange(`Postn Transcript`) %>%
    mutate(x = row_number())

  y_df <- qPCR_summary %>%
    group_by(`Postn Transcript`) %>%
    summarise(y_base = max(Mean + SEM, na.rm = TRUE), .groups = "drop")

  bracket_df <- stat_test %>%
    left_join(x_df, by = "Postn Transcript") %>%
    left_join(y_df, by = "Postn Transcript") %>%
    mutate(
      xmin = x - offset,
      xmax = case_when(
        comparison == "C3 vs C0" ~ x,
        comparison == "C7 vs C0" ~ x + offset
      ),
      y = case_when(
        comparison == "C3 vs C0" ~ y_base + step,
        comparison == "C7 vs C0" ~ y_base + 2 * step
      )
    )

  p_iso <- p_iso +
    geom_segment(
      data = bracket_df,
      aes(x = xmin, xend = xmax, y = y, yend = y),
      inherit.aes = FALSE,
      linewidth = 0.3
    ) +
    geom_segment(
      data = bracket_df,
      aes(x = xmin, xend = xmin, y = y, yend = y - tick),
      inherit.aes = FALSE,
      linewidth = 0.3
    ) +
    geom_segment(
      data = bracket_df,
      aes(x = xmax, xend = xmax, y = y, yend = y - tick),
      inherit.aes = FALSE,
      linewidth = 0.3
    ) +
    geom_text(
      data = bracket_df,
      aes(x = (xmin + xmax) / 2, y = y, label = sig),
      inherit.aes = FALSE,
      vjust = 0,
      size = 2
    ) +
    expand_limits(y = max(bracket_df$y, na.rm = TRUE) + step)

  save_panel(
    p_iso,
    "Fig6F_Postn_qPCR.png",
    width_mm = 90,
    height_mm = 55
  )

  readr::write_csv(
    qPCR_data,
    file.path(figure_dir, "Fig6F_Postn_qPCR_source_data.csv")
  )

  readr::write_csv(
    qPCR_summary,
    file.path(figure_dir, "Fig6F_Postn_qPCR_summary.csv")
  )

  readr::write_csv(
    stat_test,
    file.path(figure_dir, "Fig6F_Postn_qPCR_t_tests.csv")
  )
}

message("Figure 6 plotting complete. Outputs saved to: ", figure_dir)
