#!/usr/bin/env Rscript

# =============================================================================
# Figure 4: Heterogeneous isoform regulation across nerve-resident cell types
#
# Panels generated by this script:
#   A: UMAP with broad compartment annotations
#   B: Cell proportion bar plot across time points
#   C: Multi-DET enrichment dot plot across cell types
#   I: Mbp-Golli and Mbp-Classic DotPlot
#   J: Mbp-Golli and Mbp-Classic FeaturePlots across time points
#
# Panels generated by shared/other scripts:
#   D: Plotting_isoform_proportion.R using Fn1 as input
#   E/G: Plotting_isoform_trackplot.R using Fn1 and Mbp isoforms as input
#   F: Plotting_isoform_expression.R using Mbp as input
#   H: Mbp custom reference schematic created separately using BioRender
#
# =============================================================================

suppressPackageStartupMessages({
  library(Seurat)
  library(tidyverse)
  library(patchwork)
  library(RColorBrewer)
  library(grid)
})

# =============================================================================
# User-defined files/directories
# =============================================================================

single_cell_results_dir <- "/path/to/single_cell_results"        # <-- MODIFY HERE
figure_dir <- "/path/to/Figure_4_output"                         # <-- MODIFY HERE

seurat_object_path <- file.path(
  single_cell_results_dir,
  "integrated_annotated_seurat_object.rds"
)                                                                 # <-- MODIFY HERE IF NEEDED

enrichment_path <- file.path(
  single_cell_results_dir,
  "multi_DET_cell_type_enrichment_results.csv"
)                                                                 # <-- MODIFY HERE IF NEEDED

dir.create(figure_dir, recursive = TRUE, showWarnings = FALSE)

# =============================================================================
# User-adjustable plotting parameters
# =============================================================================

cell_type_order <- c(                                             # <-- MODIFY HERE IF NEEDED
  "Endoneurial",
  "Epineurial",
  "Perineurial",
  "Schwann Cells",
  "Immune",
  "Pericytes/VSMCs",
  "Endothelial"
)

timepoint_order <- c("C0", "C3", "C7")                           # <-- MODIFY HERE IF NEEDED

timepoint_colors <- c(                                            # <-- MODIFY HERE IF NEEDED
  C0 = "#0072B2",
  C3 = "#E69F00",
  C7 = "#66BD63"
)

mbp_features <- c("Mbp-Classic", "Mbp-Golli")                    # <-- MODIFY HERE IF NEEDED

# =============================================================================
# Input checks
# =============================================================================

if (!file.exists(seurat_object_path)) {
  stop("Missing Seurat object: ", seurat_object_path, call. = FALSE)
}

# =============================================================================
# Helper functions
# =============================================================================

save_panel <- function(plot, filename, width_mm, height_mm) {
  ggsave(
    filename = file.path(figure_dir, filename),
    plot = plot,
    width = width_mm,
    height = height_mm,
    units = "mm",
    dpi = 600,
    bg = "white"
  )
}

theme_clean_axis <- function(base_size = 8) {
  theme_minimal(base_size = base_size) +
    theme(
      panel.grid.major = element_blank(),
      panel.grid.minor = element_blank(),
      axis.line = element_line(color = "black", linewidth = 0.3),
      axis.ticks = element_line(color = "black", linewidth = 0.3),
      legend.title = element_blank()
    )
}

# =============================================================================
# Load Seurat object
# =============================================================================

obj <- readRDS(seurat_object_path)

# =============================================================================
# Figure 4A: UMAP broad cell-type annotations
# =============================================================================

p_umap <- DimPlot(
  obj,
  reduction = "umap.harmony",
  group.by = "annotations",
  label = TRUE,
  label.size = 2.2,
  pt.size = 1e-10,
  raster = FALSE
) +
  ggtitle("UMAP of Injured Sciatic Nerves") +
  theme_void() +
  theme(
    plot.title = element_text(size = 8, face = "bold", hjust = 0.5),
    legend.position = "none"
  )

save_panel(
  p_umap,
  "Fig4A_UMAP_broad_annotations.png",
  width_mm = 60,
  height_mm = 60
)

# =============================================================================
# Figure 4B: Cell composition bar plot
# =============================================================================

cell_prop_df <- table(obj$annotations, obj$timepoint) %>%
  as.data.frame()

colnames(cell_prop_df) <- c("cell_type", "timepoint", "Freq")

cell_prop_df <- cell_prop_df %>%
  mutate(
    timepoint = factor(timepoint, levels = timepoint_order),
    cell_type = factor(cell_type, levels = cell_type_order)
  )

p_bar <- ggplot(
  cell_prop_df,
  aes(x = timepoint, y = Freq, fill = cell_type)
) +
  geom_col(
    position = "fill",
    width = 0.85,
    color = "black",
    linewidth = 0.3
  ) +
  xlab(NULL) +
  ylab("Proportion") +
  ggtitle("Cell Composition") +
  theme_clean_axis(base_size = 8) +
  theme(
    plot.title = element_text(size = 10, face = "bold", hjust = 0.5),
    axis.text.x = element_text(size = 9, face = "bold"),
    axis.text.y = element_text(size = 8),
    axis.title = element_text(size = 9),
    legend.text = element_text(size = 8)
  )

save_panel(
  p_bar,
  "Fig4B_Cell_composition.png",
  width_mm = 80,
  height_mm = 70
)

readr::write_csv(
  cell_prop_df,
  file.path(figure_dir, "Fig4B_Cell_composition_source_data.csv")
)

# =============================================================================
# Figure 4C: Multi-DET cell-type enrichment dot plot
# =============================================================================

if (file.exists(enrichment_path)) {
  enrichment_df <- readr::read_csv(enrichment_path, show_col_types = FALSE) %>%
    mutate(
      contrast = factor(
        contrast,
        levels = c("C3_vs_C0", "C7_vs_C0"),
        labels = c("C3 vs C0", "C7 vs C0")
      ),
      cell_type = str_replace_all(cell_type, "Pericytes VSMCs", "Pericytes/VSMCs"),
      cell_type = factor(cell_type, levels = cell_type_order)
    )

  p_enrichment <- ggplot(
    enrichment_df,
    aes(
      x = contrast,
      y = cell_type,
      size = odds_ratio,
      color = neg_log10_FDR
    )
  ) +
    geom_point(alpha = 0.9) +
    scale_size_continuous(
      name = "Odds ratio",
      range = c(1.5, 7)
    ) +
    scale_color_gradient(
      name = "-log10(FDR)"
    ) +
    xlab(NULL) +
    ylab(NULL) +
    theme_minimal(base_size = 8) +
    theme(
      axis.text.x = element_text(size = 8, face = "bold"),
      axis.text.y = element_text(size = 8),
      panel.grid.major = element_line(linewidth = 0.2),
      panel.grid.minor = element_blank(),
      legend.title = element_text(size = 7),
      legend.text = element_text(size = 6)
    )

  save_panel(
    p_enrichment,
    "Fig4C_MultiDET_cell_type_enrichment.png",
    width_mm = 85,
    height_mm = 65
  )
} else {
  warning("Enrichment file not found. Skipping Figure 4C: ", enrichment_path)
}

# =============================================================================
# Figure 4I: Mbp-Golli / Mbp-Classic DotPlot
# =============================================================================

available_mbp <- mbp_features[mbp_features %in% rownames(obj)]

if (length(available_mbp) > 0) {
  p_dot_mbp <- DotPlot(
    obj,
    features = available_mbp,
    group.by = "annotations"
  ) +
    xlab(NULL) +
    ylab(NULL) +
    coord_flip() +
    scale_color_gradientn(
      colors = rev(RColorBrewer::brewer.pal(11, "Spectral"))
    ) +
    theme_minimal(base_size = 7) +
    theme(
      axis.line = element_line(color = "black", linewidth = 0.3),
      axis.ticks = element_line(color = "black", linewidth = 0.3),
      axis.text.x = element_text(angle = 45, hjust = 1, size = 6),
      panel.grid = element_blank(),
      axis.text.y = element_text(size = 6, face = "bold"),
      legend.key.size = unit(2.5, "mm"),
      legend.text = element_text(size = 5),
      legend.title = element_text(size = 5)
    )

  save_panel(
    p_dot_mbp,
    "Fig4I_DotPlot_Mbp_Golli_Classic.png",
    width_mm = 100,
    height_mm = 40
  )
} else {
  warning("None of the requested Mbp features were found in the Seurat object.")
}

# =============================================================================
# Figure 4J: Mbp-Golli / Mbp-Classic FeaturePlots split by time point
# =============================================================================

for (feature in available_mbp) {
  plot_list <- lapply(timepoint_order, function(tp) {
    obj_sub <- subset(obj, subset = timepoint == tp)

    FeaturePlot(
      obj_sub,
      features = feature,
      reduction = "umap.harmony",
      order = FALSE,
      pt.size = 0.01,
      raster = FALSE
    ) +
      scale_color_gradientn(
        colors = rev(RColorBrewer::brewer.pal(11, "Spectral"))
      ) +
      ggtitle(paste(feature, "-", tp)) +
      theme(
        legend.position = "right",
        plot.title = element_text(size = 10, face = "bold"),
        axis.title = element_text(size = 8),
        axis.text = element_text(size = 6),
        legend.title = element_text(size = 8),
        legend.text = element_text(size = 6)
      )
  })

  p_feature <- patchwork::wrap_plots(plot_list, ncol = length(timepoint_order))

  save_panel(
    p_feature,
    paste0("Fig4J_FeaturePlot_", feature, ".png"),
    width_mm = 170,
    height_mm = 60
  )
}

message("Figure 4 plotting complete. Outputs saved to: ", figure_dir)
