#!/usr/bin/env Rscript

################################################################################
# Supplementary Figure 4
#
# Purpose:
#   Generate supplementary DGE/DTE overlap outputs.
#
# Panels:
#   S4A: DGE/DTE Venn diagrams
#   S4B-C: DGE/DTE volcano plots generated by modifying code in Figure_3.R
#
################################################################################

suppressPackageStartupMessages({
  library(tidyverse)
  library(VennDiagram)
  library(grid)
})

# ==============================================================================
# User-defined directories
# ==============================================================================

short_read_dir <- "/path/to/short_read_results"                 # <-- MODIFY HERE
long_read_dir <- "/path/to/isoform_analysis_results"            # <-- MODIFY HERE
overlap_dir <- "/path/to/overlap_output"                        # <-- MODIFY HERE
figure_dir <- "/path/to/supplementary_figure_output"            # <-- MODIFY HERE

dir.create(overlap_dir, recursive = TRUE, showWarnings = FALSE)
dir.create(figure_dir, recursive = TRUE, showWarnings = FALSE)

# ==============================================================================
# Parameters
# ==============================================================================

padj_cutoff <- 0.05                                             # <-- MODIFY HERE IF NEEDED
lfc_cutoff <- 1                                                 # <-- MODIFY HERE IF NEEDED

comparison_config <- list(
  C3 = list(
    short_read_file = "C3_Injured_vs_C0_results.csv",
    long_read_file = "C3_vs_C0_isoform_results.csv",
    contrast_label = "C3 Injured vs. C0 Control"
  ),
  C7 = list(
    short_read_file = "C7_Injured_vs_C0_results.csv",
    long_read_file = "C7_vs_C0_isoform_results.csv",
    contrast_label = "C7 Injured vs. C0 Control"
  )
)

# ==============================================================================
# Helper functions
# ==============================================================================

filter_significant <- function(res) {
  res %>%
    filter(!is.na(padj), padj < padj_cutoff, abs(log2FoldChange) > lfc_cutoff)
}

make_venn <- function(gene_sig, transcript_sig, title, filename) {
  venn_plot <- venn.diagram(
    x = list(
      DGE = unique(gene_sig$ensembl_id),
      DTE = unique(transcript_sig$associated_gene)
    ),
    filename = NULL,
    fill = c("skyblue", "lightyellow"),
    alpha = 0.5,
    cex = 1.5,
    cat.cex = 1.5,
    main = title,
    main.cex = 2
  )

  png(
    filename = file.path(figure_dir, filename),
    width = 70,
    height = 70,
    units = "mm",
    res = 600,
    bg = "white"
  )

  grid.newpage()
  grid.draw(venn_plot)
  dev.off()
}

# ==============================================================================
# Figure S4a: DGE/DTE overlap and Venn diagrams
# ==============================================================================

for (comparison in names(comparison_config)) {
  cfg <- comparison_config[[comparison]]

  gene_file <- file.path(short_read_dir, cfg$short_read_file)
  transcript_file <- file.path(long_read_dir, cfg$long_read_file)

  if (!file.exists(gene_file)) stop("Missing short-read file: ", gene_file)
  if (!file.exists(transcript_file)) stop("Missing long-read transcript file: ", transcript_file)

  gene_res <- readr::read_csv(gene_file, show_col_types = FALSE)
  transcript_res <- readr::read_csv(transcript_file, show_col_types = FALSE)

  gene_sig <- filter_significant(gene_res)
  transcript_sig <- filter_significant(transcript_res)

  DGE_ids <- unique(gene_sig$gene_symbol)
  DTE_ids <- unique(transcript_sig$gene_symbol)

  shared_ids <- intersect(DGE_ids, DTE_ids)
  dge_only_ids <- setdiff(DGE_ids, DTE_ids)
  dte_only_ids <- setdiff(DTE_ids, DGE_ids)

  dge_only_df <- gene_sig %>%
    filter(gene_symbol %in% dge_only_ids)

  gene_shared <- gene_sig %>%
    filter(gene_symbol %in% shared_ids)

  transcript_shared <- transcript_sig %>%
    filter(gene_symbol %in% shared_ids)

  shared_df <- left_join(
    transcript_shared,
    gene_shared,
    by = "gene_symbol",
    suffix = c("_transcript", "_gene")
  )

  dte_only_df <- transcript_sig %>%
    filter(gene_symbol %in% dte_only_ids)

  write_csv(
    dge_only_df,
    file.path(overlap_dir, paste0(comparison, "_Injured_vs_C0_DGE_only_genes.csv"))
  )

  write_csv(
    shared_df,
    file.path(overlap_dir, paste0(comparison, "_Injured_vs_C0_DGE_shared_genes.csv"))
  )

  write_csv(
    dte_only_df,
    file.path(overlap_dir, paste0(comparison, "_Injured_vs_C0_DTE_only_genes.csv"))
  )

  isoform_summary <- transcript_sig %>%
    group_by(gene_symbol) %>%
    summarise(
      num_isoforms = n(),
      transcript_symbols = paste(unique(transcript_symbol), collapse = "; "),
      .groups = "drop"
    ) %>%
    mutate(shared_with_DGE = if_else(gene_symbol %in% shared_ids, "Yes", "No")) %>%
    arrange(desc(num_isoforms), gene_symbol)

  write_csv(
    isoform_summary,
    file.path(overlap_dir, paste0(comparison, "_DTE_isoform_number_shared_summary.csv"))
  )

  make_venn(
    gene_sig = gene_sig,
    transcript_sig = transcript_sig,
    title = cfg$contrast_label,
    filename = paste0("FigS4a_", comparison, "_DGE_DTE_Venn.png")
  )
}

# ==============================================================================
# Figure S4b-c
# ==============================================================================

panel_note <- tibble::tribble(
  ~panel, ~description, ~script,
  "S4b-c", "DGE and DTE volcano plots", "Figures/Figure_3.R"
)

print(panel_note)

