#!/usr/bin/env Rscript

################################################################################
# Supplementary Figure 5
#
# Purpose:
#   Generate supplementary single-cell plots.
#
# Panels:
#   S5a: UMAP detailed cell types
#   S5b: Timepoint-highlighted UMAPs
#   S5c: Detailed marker dot plot
#   S5d: Feature plots generated by Figure_4.R
#   S5e-f: Mbp-Golli / Mbp-Classic violin plots
#
################################################################################

suppressPackageStartupMessages({
  library(Seurat)
  library(tidyverse)
  library(RColorBrewer)
  library(grid)
})

# ==============================================================================
# User-defined files/directories
# ==============================================================================

single_cell_results_dir <- "/path/to/single_cell_results"        # <-- MODIFY HERE
figure_dir <- "/path/to/supplementary_figure_output"             # <-- MODIFY HERE

seurat_object_path <- file.path(
  single_cell_results_dir,
  "integrated_annotated_seurat_object.rds"
)                                                                 # <-- MODIFY HERE IF NEEDED

dir.create(figure_dir, recursive = TRUE, showWarnings = FALSE)

if (!file.exists(seurat_object_path)) {
  stop("Missing Seurat object: ", seurat_object_path)
}

# ==============================================================================
# Load object
# ==============================================================================

obj <- readRDS(seurat_object_path)

# ==============================================================================
# Figure S5a: UMAP detailed cell types
# ==============================================================================

p_umap_detailed <- DimPlot(
  obj,
  reduction = "umap.harmony",
  group.by = "detailed_annotations",
  label = TRUE,
  label.size = 2,
  pt.size = 1e-10,
  raster = FALSE
) +
  ggtitle("UMAP of Injured Sciatic Nerves") +
  theme_void() +
  theme(
    plot.title = element_text(size = 8, face = "bold", hjust = 0.5),
    legend.position = "none"
  )

ggsave(
  file.path(figure_dir, "FigS5A_UMAP_detailed_annotations.png"),
  p_umap_detailed,
  width = 90,
  height = 90,
  units = "mm",
  dpi = 600,
  bg = "white"
)

# ==============================================================================
# Figure S5b: Highlight each timepoint
# ==============================================================================

tp_cols <- c(
  C0 = "#0072B2",
  C3 = "#E69F00",
  C7 = "#66BD63"
)

for (tp in names(tp_cols)) {
  obj$highlight <- factor(
    obj$timepoint == tp,
    levels = c(FALSE, TRUE)
  )

  p <- DimPlot(
    obj,
    reduction = "umap.harmony",
    group.by = "highlight",
    cols = c("FALSE" = "grey85", "TRUE" = tp_cols[[tp]]),
    pt.size = 1e-10,
    order = TRUE,
    raster = FALSE
  ) +
    ggtitle(tp) +
    theme_void() +
    theme(
      plot.title = element_text(size = 20, face = "bold", hjust = 0.5),
      legend.position = "none"
    )

  ggsave(
    file.path(figure_dir, paste0("FigS5B_UMAP_highlight_", tp, ".png")),
    p,
    width = 90,
    height = 90,
    units = "mm",
    dpi = 600,
    bg = "white"
  )
}

# ==============================================================================
# Figure S5c: Detailed marker dot plot
# ==============================================================================

detailed_markers <- c(
  "Ms4a2", "Cpa3",
  "Cxcr2", "S100a9", "Lcn2",
  "Ly6c2", "Siglech",
  "Mki67", "Top2a",
  "Ncr1", "Klra7",
  "Cldn1", "Cxadr", "Mpzl2",
  "Cd3g", "Lat",
  "Pecam1", "Vwf", "Eng",
  "Gas1", "Angptl1", "Cilp", "Pi16", "Dpt", "Pcolce2",
  "Acta2", "Des", "Notch3",
  "Cd209a", "Napsa",
  "Chil3", "Klra2", "Trem2", "Fcgr1", "C1qa",
  "Sox10", "Mpz", "Prx", "Slc35f1", "Scn7a",
  "Sox9", "Bmp7", "Abca6"
)                                                                 # <-- MODIFY HERE IF NEEDED

available_markers <- detailed_markers[detailed_markers %in% rownames(obj)]

p_dot_detailed <- DotPlot(
  obj,
  features = available_markers,
  group.by = "detailed_annotations"
) +
  xlab(NULL) +
  ylab(NULL) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  scale_color_gradientn(colors = rev(RColorBrewer::brewer.pal(11, "Spectral")))

ggsave(
  file.path(figure_dir, "FigS5C_DotPlot_detailed_markers.png"),
  p_dot_detailed,
  width = 350,
  height = 170,
  units = "mm",
  dpi = 600,
  bg = "white"
)

# ==============================================================================
# Figure S5d
# ==============================================================================

gene_of_interest <- c("Fn1")
timepoint <- c("C0",  "C3", "C7")

plot_list <- lapply(timepoint, function(time) {
  FeaturePlot(snRNA.annotated[, snRNA.annotated$timepoint == time], 
              features = gene_of_interest, 
              order = F, 
              pt.size = 0.01, raster = F) +
    scale_color_gradientn(colors = rev(brewer.pal(11, "Spectral"))) +
    theme(legend.position = "right", 
          plot.title = element_text(size = 10, face = "bold"),
          axis.title = element_text(size = 8),
          axis.text = element_text(size = 6),
          legend.title = element_text(size = 8),
          legend.text = element_text(size = 6)) +
    ggtitle(paste(gene_of_interest, "-", time))
})

wrap_plots(plot_list, ncol = 3)

ggsave(
  file.path(figure_dir, paste0("FigS5D_FeaturePlot_", gene_of_interest, ".png")),
  plot_list,
  width = 170,
  height = 60,
  units = "mm",
  dpi = 600,
  bg = "white"
)

# ==============================================================================
# Figure S5e-f: Mbp-Golli / Mbp-Classic violin plots
# ==============================================================================

mbp_features <- c("Mbp-Golli", "Mbp-Classic")                    # <-- MODIFY HERE IF NEEDED

for (feature in mbp_features) {
  if (feature %in% rownames(obj)) {
    p_vln <- VlnPlot(
      obj,
      features = feature,
      group.by = "annotations",
      raster = FALSE
    ) +
      xlab(NULL) +
      ggtitle(feature) +
      theme(legend.position = "none")

    ggsave(
      file.path(figure_dir, paste0("FigS5_VlnPlot_", feature, ".png")),
      p_vln,
      width = 200,
      height = 90,
      units = "mm",
      dpi = 600,
      bg = "white"
    )
  } else {
    warning("Feature not found in Seurat object: ", feature)
  }
}

message("Supplementary Figure 5 complete.")
