#!/usr/bin/env Rscript

# =============================================================================
# Gene-Level Differential Expression Analysis from Isoform Counts with DESeq2
# =============================================================================
#
# Purpose:
#   This script builds gene-level counts by summing the isoform-level counts
#   used for the DTE analysis, then performs differential gene expression (DGE)
#   analysis. Gene- and transcript-level results are therefore derived from the
#   same quantification.
#
#   Isoforms are grouped by Ensembl gene ID (`associated_gene`), so all isoforms
#   of a gene contribute to a single gene-level count.
#
# Input:
#   - all_transcripts_with_associated_genes_count.tsv
#     generated by Generating_Isoform_Count_Matrix.R
#
# Outputs:
#   - C3_vs_C0_inferred_gene_results.csv
#   - C7_vs_C0_inferred_gene_results.csv
#   - C7_vs_C3_inferred_gene_results.csv
#
# =============================================================================

suppressPackageStartupMessages({
  library(DESeq2)
  library(tidyverse)
})

# -----------------------------
# User-defined files/directories
# -----------------------------

results_dir <- "/path/to/output_directory"                         # <-- MODIFY HERE

count_path <- file.path(
  results_dir,
  "all_transcripts_with_associated_genes_count.tsv"
)                                                                   # <-- MODIFY HERE IF NEEDED

dir.create(results_dir, recursive = TRUE, showWarnings = FALSE)

# -----------------------------
# Input check
# -----------------------------

if (!file.exists(count_path)) {
  stop("Count matrix not found: ", count_path, call. = FALSE)
}

# =============================================================================
# Build gene-level count matrix
# =============================================================================

isoform_counts <- readr::read_tsv(count_path, show_col_types = FALSE)

metadata_cols <- c(
  "transcript_id",
  "transcript_symbol",
  "associated_gene",
  "gene_symbol"
)

missing_cols <- setdiff(metadata_cols, colnames(isoform_counts))

if (length(missing_cols) > 0) {
  stop(
    "Missing required metadata columns in count table: ",
    paste(missing_cols, collapse = ", "),
    call. = FALSE
  )
}

sample_cols <- setdiff(colnames(isoform_counts), metadata_cols)

gene_counts <- isoform_counts %>%
  filter(!is.na(associated_gene), associated_gene != "") %>%
  group_by(associated_gene) %>%
  summarise(
    across(all_of(sample_cols), ~ sum(.x, na.rm = TRUE)),
    .groups = "drop"
  )

# One gene symbol per Ensembl gene ID, preferring a gene symbol over an ID.
gene_symbol_lookup <- isoform_counts %>%
  filter(!is.na(associated_gene), !is.na(gene_symbol)) %>%
  distinct(associated_gene, gene_symbol) %>%
  mutate(is_id = str_starts(gene_symbol, "ENSMUSG")) %>%
  arrange(associated_gene, is_id) %>%
  distinct(associated_gene, .keep_all = TRUE) %>%
  dplyr::select(associated_gene, gene_symbol)

count_data <- gene_counts %>%
  dplyr::select(all_of(sample_cols)) %>%
  mutate(across(everything(), round)) %>%
  as.data.frame()

rownames(count_data) <- gene_counts$associated_gene

message("Genes in count matrix: ", nrow(count_data))

# =============================================================================
# Prepare sample metadata
# =============================================================================

sample_info <- tibble(sample = sample_cols) %>%
  mutate(
    time_point = str_extract(sample, "^C\\d+"),
    treatment = if_else(str_detect(sample, "Injured"), "Injured", "Control"),
    group = factor(
      paste0(time_point, "_", treatment),
      levels = c("C0_Control", "C3_Injured", "C7_Injured")
    )
  ) %>%
  as.data.frame()

rownames(sample_info) <- sample_info$sample

if (any(is.na(sample_info$group))) {
  stop("Some samples could not be assigned to groups. Check sample names.", call. = FALSE)
}

# =============================================================================
# Run DESeq2
# =============================================================================

dds <- DESeqDataSetFromMatrix(
  countData = count_data,
  colData = sample_info,
  design = ~ group
)

dds <- DESeq(dds)

# =============================================================================
# Extract contrast-level DESeq2 results
# =============================================================================

extract_deseq_results <- function(dds, numerator, denominator) {
  norm_counts <- counts(dds, normalized = TRUE)

  results(dds, contrast = c("group", numerator, denominator)) %>%
    as.data.frame() %>%
    rownames_to_column("associated_gene") %>%
    left_join(gene_symbol_lookup, by = "associated_gene") %>%
    mutate(
      gene_symbol = coalesce(gene_symbol, associated_gene),
      mean_num = rowMeans(
        norm_counts[, colData(dds)$group == numerator, drop = FALSE]
      ),
      mean_den = rowMeans(
        norm_counts[, colData(dds)$group == denominator, drop = FALSE]
      )
    ) %>%
    relocate(gene_symbol, associated_gene) %>%
    arrange(padj)
}

result_list <- list(
  C3_vs_C0 = extract_deseq_results(dds, "C3_Injured", "C0_Control"),
  C7_vs_C0 = extract_deseq_results(dds, "C7_Injured", "C0_Control"),
  C7_vs_C3 = extract_deseq_results(dds, "C7_Injured", "C3_Injured")
)

purrr::iwalk(
  result_list,
  ~ readr::write_csv(
    .x,
    file.path(results_dir, paste0(.y, "_inferred_gene_results.csv"))
  )
)

message("Gene-level DGE analysis complete. Results saved to: ", results_dir)
